// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analyze.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AnalyzeApiRequest represents the request to the API HTTP service
type AnalyzeApiRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	AnalyzeTemplateId    string   `protobuf:"bytes,2,opt,name=analyzeTemplateId" json:"analyzeTemplateId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalyzeApiRequest) Reset()         { *m = AnalyzeApiRequest{} }
func (m *AnalyzeApiRequest) String() string { return proto.CompactTextString(m) }
func (*AnalyzeApiRequest) ProtoMessage()    {}
func (*AnalyzeApiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyze_67b65ff3d58fe642, []int{0}
}
func (m *AnalyzeApiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeApiRequest.Unmarshal(m, b)
}
func (m *AnalyzeApiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeApiRequest.Marshal(b, m, deterministic)
}
func (dst *AnalyzeApiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeApiRequest.Merge(dst, src)
}
func (m *AnalyzeApiRequest) XXX_Size() int {
	return xxx_messageInfo_AnalyzeApiRequest.Size(m)
}
func (m *AnalyzeApiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeApiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeApiRequest proto.InternalMessageInfo

func (m *AnalyzeApiRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *AnalyzeApiRequest) GetAnalyzeTemplateId() string {
	if m != nil {
		return m.AnalyzeTemplateId
	}
	return ""
}

// AnalyzeRequest represents the request to the analyze service via GRPC
type AnalyzeRequest struct {
	Value                string           `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	AnalyzeTemplate      *AnalyzeTemplate `protobuf:"bytes,2,opt,name=analyzeTemplate" json:"analyzeTemplate,omitempty"`
	MinProbability       string           `protobuf:"bytes,3,opt,name=minProbability" json:"minProbability,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AnalyzeRequest) Reset()         { *m = AnalyzeRequest{} }
func (m *AnalyzeRequest) String() string { return proto.CompactTextString(m) }
func (*AnalyzeRequest) ProtoMessage()    {}
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyze_67b65ff3d58fe642, []int{1}
}
func (m *AnalyzeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeRequest.Unmarshal(m, b)
}
func (m *AnalyzeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeRequest.Marshal(b, m, deterministic)
}
func (dst *AnalyzeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeRequest.Merge(dst, src)
}
func (m *AnalyzeRequest) XXX_Size() int {
	return xxx_messageInfo_AnalyzeRequest.Size(m)
}
func (m *AnalyzeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeRequest proto.InternalMessageInfo

func (m *AnalyzeRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *AnalyzeRequest) GetAnalyzeTemplate() *AnalyzeTemplate {
	if m != nil {
		return m.AnalyzeTemplate
	}
	return nil
}

func (m *AnalyzeRequest) GetMinProbability() string {
	if m != nil {
		return m.MinProbability
	}
	return ""
}

// AnalyzeResponse represents the analyze service response
type AnalyzeResponse struct {
	AnalyzeResults       []*AnalyzeResult `protobuf:"bytes,1,rep,name=analyzeResults" json:"analyzeResults,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AnalyzeResponse) Reset()         { *m = AnalyzeResponse{} }
func (m *AnalyzeResponse) String() string { return proto.CompactTextString(m) }
func (*AnalyzeResponse) ProtoMessage()    {}
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyze_67b65ff3d58fe642, []int{2}
}
func (m *AnalyzeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeResponse.Unmarshal(m, b)
}
func (m *AnalyzeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeResponse.Marshal(b, m, deterministic)
}
func (dst *AnalyzeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeResponse.Merge(dst, src)
}
func (m *AnalyzeResponse) XXX_Size() int {
	return xxx_messageInfo_AnalyzeResponse.Size(m)
}
func (m *AnalyzeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeResponse proto.InternalMessageInfo

func (m *AnalyzeResponse) GetAnalyzeResults() []*AnalyzeResult {
	if m != nil {
		return m.AnalyzeResults
	}
	return nil
}

func init() {
	proto.RegisterType((*AnalyzeApiRequest)(nil), "types.AnalyzeApiRequest")
	proto.RegisterType((*AnalyzeRequest)(nil), "types.AnalyzeRequest")
	proto.RegisterType((*AnalyzeResponse)(nil), "types.AnalyzeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnalyzeServiceClient is the client API for AnalyzeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnalyzeServiceClient interface {
	Apply(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type analyzeServiceClient struct {
	cc *grpc.ClientConn
}

func NewAnalyzeServiceClient(cc *grpc.ClientConn) AnalyzeServiceClient {
	return &analyzeServiceClient{cc}
}

func (c *analyzeServiceClient) Apply(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, "/types.AnalyzeService/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyzeServiceServer is the server API for AnalyzeService service.
type AnalyzeServiceServer interface {
	Apply(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
}

func RegisterAnalyzeServiceServer(s *grpc.Server, srv AnalyzeServiceServer) {
	s.RegisterService(&_AnalyzeService_serviceDesc, srv)
}

func _AnalyzeService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzeServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.AnalyzeService/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzeServiceServer).Apply(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnalyzeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.AnalyzeService",
	HandlerType: (*AnalyzeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _AnalyzeService_Apply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analyze.proto",
}

func init() { proto.RegisterFile("analyze.proto", fileDescriptor_analyze_67b65ff3d58fe642) }

var fileDescriptor_analyze_67b65ff3d58fe642 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x09, 0x25, 0x48, 0x5c, 0x21, 0x55, 0x4f, 0xa5, 0x8a, 0x32, 0x55, 0x19, 0x50, 0x07,
	0x94, 0x21, 0x2c, 0x0c, 0x0c, 0x64, 0x84, 0x05, 0x14, 0xe0, 0x07, 0x38, 0xe5, 0x86, 0x48, 0x4e,
	0x6c, 0xe2, 0x4b, 0x45, 0xf8, 0x15, 0xfc, 0x64, 0x24, 0xc7, 0x44, 0xaa, 0xbb, 0x25, 0xef, 0xbd,
	0xfb, 0xee, 0xd9, 0x86, 0x2b, 0xd1, 0x0a, 0x39, 0xfc, 0x50, 0xa6, 0x3b, 0xc5, 0x0a, 0x43, 0x1e,
	0x34, 0x99, 0xe4, 0x72, 0xa7, 0x9a, 0x46, 0xb5, 0xa3, 0x98, 0x44, 0x4c, 0x8d, 0x96, 0x82, 0x5d,
	0x28, 0xfd, 0x80, 0x65, 0x31, 0x4e, 0x15, 0xba, 0x2e, 0xe9, 0xab, 0x27, 0xc3, 0x88, 0x70, 0xc6,
	0xf4, 0xcd, 0x71, 0xb0, 0x09, 0xb6, 0x17, 0xa5, 0xfd, 0xc6, 0x5b, 0x58, 0x3a, 0xfc, 0xbb, 0x23,
	0x3c, 0x7d, 0xc6, 0xa7, 0x36, 0x70, 0x6c, 0xa4, 0xbf, 0x01, 0x44, 0x8e, 0xfb, 0x0f, 0x5d, 0x41,
	0xb8, 0x17, 0xb2, 0x27, 0x47, 0x1d, 0x7f, 0xf0, 0x11, 0x16, 0xde, 0xb4, 0x85, 0xce, 0xf3, 0x75,
	0x66, 0xeb, 0x67, 0xc5, 0xa1, 0x5b, 0xfa, 0x71, 0xbc, 0x81, 0xa8, 0xa9, 0xdb, 0xd7, 0x4e, 0x55,
	0xa2, 0xaa, 0x65, 0xcd, 0x43, 0x3c, 0xb3, 0x0b, 0x3c, 0x35, 0x7d, 0x81, 0xc5, 0xd4, 0xc8, 0x68,
	0xd5, 0x1a, 0xc2, 0x07, 0x88, 0xc4, 0x24, 0xf5, 0x92, 0x4d, 0x1c, 0x6c, 0x66, 0xdb, 0x79, 0xbe,
	0x3a, 0xdc, 0x3d, 0x9a, 0xa5, 0x97, 0xcd, 0x9f, 0xa7, 0x23, 0xbe, 0x51, 0xb7, 0xaf, 0x77, 0x84,
	0xf7, 0x10, 0x16, 0x5a, 0xcb, 0x01, 0xaf, 0x7d, 0x80, 0xbd, 0x82, 0x64, 0x7d, 0xc4, 0xb5, 0x3d,
	0xd2, 0x93, 0xea, 0xdc, 0xbe, 0xc6, 0xdd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0xd6, 0x62,
	0x88, 0xc3, 0x01, 0x00, 0x00,
}
