// Code generated by protoc-gen-go. DO NOT EDIT.
// source: anonymize-json.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AnonymizeJsonApiRequest represents the request to the API HTTP service
type AnonymizeJsonApiRequest struct {
	// The json to anonymize
	Json string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	// The json schema template id.
	// One of jsonSchemaId or jsonSchema have to be configured.
	JsonSchemaId string `protobuf:"bytes,2,opt,name=jsonSchemaId,proto3" json:"jsonSchemaId,omitempty"`
	// The analyze template id - anonymization is done according to analyzing results.
	// One of analyzeTemplateId or analyzeTemplate have to be configured.
	AnalyzeTemplateId string `protobuf:"bytes,3,opt,name=analyzeTemplateId,proto3" json:"analyzeTemplateId,omitempty"`
	// The anonymize template id - represents the anonymize configuration, which fields to anonymize and how.
	AnonymizeTemplateId string `protobuf:"bytes,4,opt,name=anonymizeTemplateId,proto3" json:"anonymizeTemplateId,omitempty"`
	// Optional parameter for running the json anonymizer without creating a schema template.
	JsonSchemaTemplate *JsonSchemaTemplate `protobuf:"bytes,5,opt,name=jsonSchemaTemplate,proto3" json:"jsonSchemaTemplate,omitempty"`
	// Optional parameter for running the analyzer without creating a template.
	AnalyzeTemplate *AnalyzeTemplate `protobuf:"bytes,6,opt,name=analyzeTemplate,proto3" json:"analyzeTemplate,omitempty"`
	// Optional parameter for running the anonymizer without creating a template.
	AnonymizeTemplate    *AnonymizeTemplate `protobuf:"bytes,7,opt,name=anonymizeTemplate,proto3" json:"anonymizeTemplate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AnonymizeJsonApiRequest) Reset()         { *m = AnonymizeJsonApiRequest{} }
func (m *AnonymizeJsonApiRequest) String() string { return proto.CompactTextString(m) }
func (*AnonymizeJsonApiRequest) ProtoMessage()    {}
func (*AnonymizeJsonApiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_anonymize_json_9931a554671c2814, []int{0}
}
func (m *AnonymizeJsonApiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnonymizeJsonApiRequest.Unmarshal(m, b)
}
func (m *AnonymizeJsonApiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnonymizeJsonApiRequest.Marshal(b, m, deterministic)
}
func (dst *AnonymizeJsonApiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnonymizeJsonApiRequest.Merge(dst, src)
}
func (m *AnonymizeJsonApiRequest) XXX_Size() int {
	return xxx_messageInfo_AnonymizeJsonApiRequest.Size(m)
}
func (m *AnonymizeJsonApiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnonymizeJsonApiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnonymizeJsonApiRequest proto.InternalMessageInfo

func (m *AnonymizeJsonApiRequest) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func (m *AnonymizeJsonApiRequest) GetJsonSchemaId() string {
	if m != nil {
		return m.JsonSchemaId
	}
	return ""
}

func (m *AnonymizeJsonApiRequest) GetAnalyzeTemplateId() string {
	if m != nil {
		return m.AnalyzeTemplateId
	}
	return ""
}

func (m *AnonymizeJsonApiRequest) GetAnonymizeTemplateId() string {
	if m != nil {
		return m.AnonymizeTemplateId
	}
	return ""
}

func (m *AnonymizeJsonApiRequest) GetJsonSchemaTemplate() *JsonSchemaTemplate {
	if m != nil {
		return m.JsonSchemaTemplate
	}
	return nil
}

func (m *AnonymizeJsonApiRequest) GetAnalyzeTemplate() *AnalyzeTemplate {
	if m != nil {
		return m.AnalyzeTemplate
	}
	return nil
}

func (m *AnonymizeJsonApiRequest) GetAnonymizeTemplate() *AnonymizeTemplate {
	if m != nil {
		return m.AnonymizeTemplate
	}
	return nil
}

type AnonymizeJsonRequest struct {
	// The json to anonymize
	Json string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	// the Json schema template.
	JsonSchema *JsonSchemaTemplate `protobuf:"bytes,2,opt,name=jsonSchema,proto3" json:"jsonSchema,omitempty"`
	// The analyze tempalte represents which fields should be analyzed in the json.
	AnalyzeTemplate *AnalyzeTemplate `protobuf:"bytes,3,opt,name=analyzeTemplate,proto3" json:"analyzeTemplate,omitempty"`
	// The anonymize template represent the anonymize configuration, which fields to anonymize and how.
	AnonymizeTemplate    *AnonymizeTemplate `protobuf:"bytes,4,opt,name=anonymizeTemplate,proto3" json:"anonymizeTemplate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AnonymizeJsonRequest) Reset()         { *m = AnonymizeJsonRequest{} }
func (m *AnonymizeJsonRequest) String() string { return proto.CompactTextString(m) }
func (*AnonymizeJsonRequest) ProtoMessage()    {}
func (*AnonymizeJsonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_anonymize_json_9931a554671c2814, []int{1}
}
func (m *AnonymizeJsonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnonymizeJsonRequest.Unmarshal(m, b)
}
func (m *AnonymizeJsonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnonymizeJsonRequest.Marshal(b, m, deterministic)
}
func (dst *AnonymizeJsonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnonymizeJsonRequest.Merge(dst, src)
}
func (m *AnonymizeJsonRequest) XXX_Size() int {
	return xxx_messageInfo_AnonymizeJsonRequest.Size(m)
}
func (m *AnonymizeJsonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnonymizeJsonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnonymizeJsonRequest proto.InternalMessageInfo

func (m *AnonymizeJsonRequest) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func (m *AnonymizeJsonRequest) GetJsonSchema() *JsonSchemaTemplate {
	if m != nil {
		return m.JsonSchema
	}
	return nil
}

func (m *AnonymizeJsonRequest) GetAnalyzeTemplate() *AnalyzeTemplate {
	if m != nil {
		return m.AnalyzeTemplate
	}
	return nil
}

func (m *AnonymizeJsonRequest) GetAnonymizeTemplate() *AnonymizeTemplate {
	if m != nil {
		return m.AnonymizeTemplate
	}
	return nil
}

func init() {
	proto.RegisterType((*AnonymizeJsonApiRequest)(nil), "types.AnonymizeJsonApiRequest")
	proto.RegisterType((*AnonymizeJsonRequest)(nil), "types.AnonymizeJsonRequest")
}

func init() {
	proto.RegisterFile("anonymize-json.proto", fileDescriptor_anonymize_json_9931a554671c2814)
}

var fileDescriptor_anonymize_json_9931a554671c2814 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xcc, 0xcb, 0xcf,
	0xab, 0xcc, 0xcd, 0xac, 0x4a, 0xd5, 0xcd, 0x2a, 0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2d, 0xa9, 0x2c, 0x48, 0x2d, 0x96, 0xe2, 0x2b, 0x49, 0xcd, 0x2d, 0xc8, 0x49, 0x2c,
	0x49, 0x85, 0x08, 0x2b, 0xb5, 0x31, 0x73, 0x89, 0x3b, 0xc2, 0xd4, 0x7b, 0x01, 0x95, 0x3b, 0x16,
	0x64, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0x80, 0x0c, 0x90, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x94, 0xb8, 0x78, 0x40, 0x74, 0x70, 0x72, 0x46,
	0x6a, 0x6e, 0xa2, 0x67, 0x8a, 0x04, 0x13, 0x58, 0x0e, 0x45, 0x4c, 0x48, 0x87, 0x4b, 0x30, 0x31,
	0x2f, 0x31, 0xa7, 0xb2, 0x2a, 0x35, 0x04, 0x6a, 0x19, 0x50, 0x21, 0x33, 0x58, 0x21, 0xa6, 0x84,
	0x90, 0x01, 0x97, 0x30, 0xdc, 0xc1, 0x48, 0xea, 0x59, 0xc0, 0xea, 0xb1, 0x49, 0x09, 0x79, 0x72,
	0x09, 0x21, 0xec, 0x83, 0x89, 0x4b, 0xb0, 0x02, 0x35, 0x70, 0x1b, 0x49, 0xea, 0x81, 0xfd, 0xa9,
	0xe7, 0x85, 0xa1, 0x20, 0x08, 0x8b, 0x26, 0x21, 0x07, 0x2e, 0x7e, 0x34, 0x17, 0x49, 0xb0, 0x81,
	0xcd, 0x11, 0x83, 0x9a, 0xe3, 0x88, 0x2a, 0x1b, 0x84, 0xae, 0x5c, 0xc8, 0x0d, 0xe4, 0x59, 0x34,
	0x37, 0x4a, 0xb0, 0x83, 0xcd, 0x90, 0x80, 0x9b, 0x81, 0x26, 0x1f, 0x84, 0xa9, 0x45, 0xe9, 0x3d,
	0x23, 0x97, 0x08, 0x4a, 0x44, 0xe0, 0x8b, 0x05, 0x4b, 0x2e, 0x2e, 0x84, 0x67, 0xc0, 0x71, 0x80,
	0xd7, 0xe7, 0x48, 0x8a, 0xb1, 0xf9, 0x98, 0x99, 0x0a, 0x3e, 0x66, 0x21, 0xd9, 0xc7, 0x49, 0x6c,
	0xe0, 0x14, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x47, 0xa2, 0x09, 0xb2, 0xb0, 0x02, 0x00,
	0x00,
}
