// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// FieldTypes for Analyzing and Anonymizing
type FieldTypesEnum int32

const (
	FieldTypesEnum_CREDIT_CARD       FieldTypesEnum = 0
	FieldTypesEnum_CRYPTO            FieldTypesEnum = 1
	FieldTypesEnum_DATE_TIME         FieldTypesEnum = 2
	FieldTypesEnum_DOMAIN_NAME       FieldTypesEnum = 3
	FieldTypesEnum_EMAIL_ADDRESS     FieldTypesEnum = 4
	FieldTypesEnum_IBAN_CODE         FieldTypesEnum = 5
	FieldTypesEnum_IP_ADDRESS        FieldTypesEnum = 6
	FieldTypesEnum_NRP               FieldTypesEnum = 7
	FieldTypesEnum_LOCATION          FieldTypesEnum = 8
	FieldTypesEnum_PERSON            FieldTypesEnum = 9
	FieldTypesEnum_PHONE_NUMBER      FieldTypesEnum = 10
	FieldTypesEnum_US_BANK_NUMBER    FieldTypesEnum = 11
	FieldTypesEnum_US_DRIVER_LICENSE FieldTypesEnum = 12
	FieldTypesEnum_US_ITIN           FieldTypesEnum = 13
	FieldTypesEnum_US_PASSPORT       FieldTypesEnum = 14
	FieldTypesEnum_US_SSN            FieldTypesEnum = 15
	FieldTypesEnum_UK_NHS            FieldTypesEnum = 16
)

var FieldTypesEnum_name = map[int32]string{
	0:  "CREDIT_CARD",
	1:  "CRYPTO",
	2:  "DATE_TIME",
	3:  "DOMAIN_NAME",
	4:  "EMAIL_ADDRESS",
	5:  "IBAN_CODE",
	6:  "IP_ADDRESS",
	7:  "NRP",
	8:  "LOCATION",
	9:  "PERSON",
	10: "PHONE_NUMBER",
	11: "US_BANK_NUMBER",
	12: "US_DRIVER_LICENSE",
	13: "US_ITIN",
	14: "US_PASSPORT",
	15: "US_SSN",
	16: "UK_NHS",
}
var FieldTypesEnum_value = map[string]int32{
	"CREDIT_CARD":       0,
	"CRYPTO":            1,
	"DATE_TIME":         2,
	"DOMAIN_NAME":       3,
	"EMAIL_ADDRESS":     4,
	"IBAN_CODE":         5,
	"IP_ADDRESS":        6,
	"NRP":               7,
	"LOCATION":          8,
	"PERSON":            9,
	"PHONE_NUMBER":      10,
	"US_BANK_NUMBER":    11,
	"US_DRIVER_LICENSE": 12,
	"US_ITIN":           13,
	"US_PASSPORT":       14,
	"US_SSN":            15,
	"UK_NHS":            16,
}

func (x FieldTypesEnum) String() string {
	return proto.EnumName(FieldTypesEnum_name, int32(x))
}
func (FieldTypesEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_2fc0f2cccb8668a9, []int{0}
}

// Anonymize image detection type
type DetectionTypeEnum int32

const (
	DetectionTypeEnum_OCR        DetectionTypeEnum = 0
	DetectionTypeEnum_AZURE_OCR  DetectionTypeEnum = 1
	DetectionTypeEnum_AZURE_FACE DetectionTypeEnum = 2
)

var DetectionTypeEnum_name = map[int32]string{
	0: "OCR",
	1: "AZURE_OCR",
	2: "AZURE_FACE",
}
var DetectionTypeEnum_value = map[string]int32{
	"OCR":        0,
	"AZURE_OCR":  1,
	"AZURE_FACE": 2,
}

func (x DetectionTypeEnum) String() string {
	return proto.EnumName(DetectionTypeEnum_name, int32(x))
}
func (DetectionTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_2fc0f2cccb8668a9, []int{1}
}

// FieldType strucy
type FieldTypes struct {
	// Field type name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Field type language code
	LanguageCode string `protobuf:"bytes,2,opt,name=languageCode,proto3" json:"languageCode,omitempty"`
	// The minScore will filter results which has lower certainty than the provided value.
	MinScore             string   `protobuf:"bytes,3,opt,name=minScore,proto3" json:"minScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldTypes) Reset()         { *m = FieldTypes{} }
func (m *FieldTypes) String() string { return proto.CompactTextString(m) }
func (*FieldTypes) ProtoMessage()    {}
func (*FieldTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_2fc0f2cccb8668a9, []int{0}
}
func (m *FieldTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldTypes.Unmarshal(m, b)
}
func (m *FieldTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldTypes.Marshal(b, m, deterministic)
}
func (dst *FieldTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldTypes.Merge(dst, src)
}
func (m *FieldTypes) XXX_Size() int {
	return xxx_messageInfo_FieldTypes.Size(m)
}
func (m *FieldTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldTypes.DiscardUnknown(m)
}

var xxx_messageInfo_FieldTypes proto.InternalMessageInfo

func (m *FieldTypes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldTypes) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *FieldTypes) GetMinScore() string {
	if m != nil {
		return m.MinScore
	}
	return ""
}

// AnalyzeResult represents the Analyze serivce findings
type AnalyzeResult struct {
	// The sensitive text result
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// The sensitive text type (supported types: FieldTypesEnum)
	Field *FieldTypes `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	// The score of the result
	Score float32 `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	// The loaction in the text of the finding
	Location             *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AnalyzeResult) Reset()         { *m = AnalyzeResult{} }
func (m *AnalyzeResult) String() string { return proto.CompactTextString(m) }
func (*AnalyzeResult) ProtoMessage()    {}
func (*AnalyzeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_2fc0f2cccb8668a9, []int{1}
}
func (m *AnalyzeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeResult.Unmarshal(m, b)
}
func (m *AnalyzeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeResult.Marshal(b, m, deterministic)
}
func (dst *AnalyzeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeResult.Merge(dst, src)
}
func (m *AnalyzeResult) XXX_Size() int {
	return xxx_messageInfo_AnalyzeResult.Size(m)
}
func (m *AnalyzeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeResult.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeResult proto.InternalMessageInfo

func (m *AnalyzeResult) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *AnalyzeResult) GetField() *FieldTypes {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *AnalyzeResult) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *AnalyzeResult) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

// The location in the text of the finding
type Location struct {
	// The location start
	Start int32 `protobuf:"zigzag32,1,opt,name=start,proto3" json:"start,omitempty"`
	// The location end
	End int32 `protobuf:"zigzag32,2,opt,name=end,proto3" json:"end,omitempty"`
	// The location length
	Length               int32    `protobuf:"zigzag32,3,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_2fc0f2cccb8668a9, []int{2}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Location) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Location) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

// Define an image with extracted bounded boxes of text/image
type Image struct {
	// The image data in bytes
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The image type JPEG/PNG/TIFF
	ImageType string `protobuf:"bytes,2,opt,name=imageType,proto3" json:"imageType,omitempty"`
	// Array of Boundingbox
	Boundingboxes []*Boundingbox `protobuf:"bytes,3,rep,name=Boundingboxes,proto3" json:"Boundingboxes,omitempty"`
	// Image Text
	Text                 string   `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_2fc0f2cccb8668a9, []int{3}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Image) GetImageType() string {
	if m != nil {
		return m.ImageType
	}
	return ""
}

func (m *Image) GetBoundingboxes() []*Boundingbox {
	if m != nil {
		return m.Boundingboxes
	}
	return nil
}

func (m *Image) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// Define an extracted bounding box text/image from images
type Boundingbox struct {
	// Pixel X location of BBox
	XLocation float32 `protobuf:"fixed32,1,opt,name=xLocation,proto3" json:"xLocation,omitempty"`
	// Width of BBox
	Width float32 `protobuf:"fixed32,2,opt,name=width,proto3" json:"width,omitempty"`
	// Pixel Y location of BBox
	YLocation float32 `protobuf:"fixed32,3,opt,name=yLocation,proto3" json:"yLocation,omitempty"`
	// Height of BBox
	Height float32 `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	// Text in BBox
	Text string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	// Start position of char in text
	StartPosition int32 `protobuf:"zigzag32,6,opt,name=startPosition,proto3" json:"startPosition,omitempty"`
	// End position of char in text
	EndPosition          int32    `protobuf:"zigzag32,7,opt,name=endPosition,proto3" json:"endPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boundingbox) Reset()         { *m = Boundingbox{} }
func (m *Boundingbox) String() string { return proto.CompactTextString(m) }
func (*Boundingbox) ProtoMessage()    {}
func (*Boundingbox) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_2fc0f2cccb8668a9, []int{4}
}
func (m *Boundingbox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boundingbox.Unmarshal(m, b)
}
func (m *Boundingbox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boundingbox.Marshal(b, m, deterministic)
}
func (dst *Boundingbox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boundingbox.Merge(dst, src)
}
func (m *Boundingbox) XXX_Size() int {
	return xxx_messageInfo_Boundingbox.Size(m)
}
func (m *Boundingbox) XXX_DiscardUnknown() {
	xxx_messageInfo_Boundingbox.DiscardUnknown(m)
}

var xxx_messageInfo_Boundingbox proto.InternalMessageInfo

func (m *Boundingbox) GetXLocation() float32 {
	if m != nil {
		return m.XLocation
	}
	return 0
}

func (m *Boundingbox) GetWidth() float32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Boundingbox) GetYLocation() float32 {
	if m != nil {
		return m.YLocation
	}
	return 0
}

func (m *Boundingbox) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Boundingbox) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Boundingbox) GetStartPosition() int32 {
	if m != nil {
		return m.StartPosition
	}
	return 0
}

func (m *Boundingbox) GetEndPosition() int32 {
	if m != nil {
		return m.EndPosition
	}
	return 0
}

func init() {
	proto.RegisterType((*FieldTypes)(nil), "types.FieldTypes")
	proto.RegisterType((*AnalyzeResult)(nil), "types.AnalyzeResult")
	proto.RegisterType((*Location)(nil), "types.Location")
	proto.RegisterType((*Image)(nil), "types.Image")
	proto.RegisterType((*Boundingbox)(nil), "types.Boundingbox")
	proto.RegisterEnum("types.FieldTypesEnum", FieldTypesEnum_name, FieldTypesEnum_value)
	proto.RegisterEnum("types.DetectionTypeEnum", DetectionTypeEnum_name, DetectionTypeEnum_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_2fc0f2cccb8668a9) }

var fileDescriptor_common_2fc0f2cccb8668a9 = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xed, 0x7c, 0x8e, 0x93, 0x74, 0xbd, 0x02, 0x14, 0x21, 0x0e, 0x55, 0x84, 0x44, 0x55,
	0xa4, 0x1e, 0xca, 0x05, 0x89, 0x93, 0x63, 0x6f, 0x55, 0xd3, 0x64, 0x6d, 0xed, 0xda, 0x48, 0x70,
	0x59, 0xdc, 0x64, 0x49, 0x2c, 0x25, 0x76, 0xd5, 0x38, 0xa2, 0xe5, 0x0f, 0x70, 0xe4, 0xc4, 0x2f,
	0xe3, 0x0f, 0xa1, 0x5d, 0x27, 0x4e, 0x7a, 0x9b, 0xf7, 0x66, 0x76, 0xde, 0x9b, 0x97, 0xc8, 0xd0,
	0x9b, 0x15, 0xeb, 0x75, 0x91, 0x5f, 0xde, 0x3f, 0x14, 0x65, 0x81, 0x9b, 0xe5, 0xd3, 0xbd, 0xdc,
	0x8c, 0xbe, 0x03, 0x5c, 0x67, 0x72, 0x35, 0x8f, 0x15, 0xc2, 0x18, 0x1a, 0x79, 0xba, 0x96, 0x43,
	0xe3, 0xcc, 0x38, 0xef, 0x32, 0x5d, 0xe3, 0x11, 0xf4, 0x56, 0x69, 0xbe, 0xd8, 0xa6, 0x0b, 0xe9,
	0x15, 0x73, 0x39, 0x34, 0x75, 0xef, 0x19, 0x87, 0x5f, 0x43, 0x67, 0x9d, 0xe5, 0x7c, 0x56, 0x3c,
	0xc8, 0xa1, 0xa5, 0xfb, 0x35, 0x1e, 0xfd, 0x31, 0xa0, 0xef, 0xe6, 0xe9, 0xea, 0xe9, 0x97, 0x64,
	0x72, 0xb3, 0x5d, 0x95, 0x4a, 0xa5, 0x94, 0x8f, 0xe5, 0x5e, 0x45, 0xd5, 0xf8, 0x1d, 0x34, 0x7f,
	0x28, 0x1f, 0x7a, 0xbd, 0x7d, 0xe5, 0x5c, 0x6a, 0x7b, 0x97, 0x07, 0x6f, 0xac, 0xea, 0xe3, 0x17,
	0xd0, 0xdc, 0xd4, 0x3a, 0x26, 0xab, 0x00, 0x7e, 0x0f, 0x9d, 0x55, 0x31, 0x4b, 0xcb, 0xac, 0xc8,
	0x87, 0x0d, 0xbd, 0xe1, 0x74, 0xb7, 0x61, 0xb2, 0xa3, 0x59, 0x3d, 0x30, 0xfa, 0x0c, 0x9d, 0x3d,
	0xab, 0xd7, 0x95, 0xe9, 0x43, 0x65, 0xc6, 0x61, 0x15, 0xc0, 0x08, 0x2c, 0x99, 0x57, 0x5e, 0x1c,
	0xa6, 0x4a, 0xfc, 0x0a, 0x5a, 0x2b, 0x99, 0x2f, 0xca, 0xa5, 0xd6, 0x75, 0xd8, 0x0e, 0x8d, 0x7e,
	0x1b, 0xd0, 0x0c, 0xd6, 0xe9, 0x42, 0xaa, 0xab, 0xe6, 0x69, 0x99, 0xea, 0x45, 0x3d, 0xa6, 0x6b,
	0xfc, 0x06, 0xba, 0x99, 0x6a, 0xaa, 0x0b, 0x76, 0xc1, 0x1d, 0x08, 0xfc, 0x11, 0xfa, 0xe3, 0x62,
	0x9b, 0xcf, 0xb3, 0x7c, 0x71, 0x57, 0x3c, 0xca, 0xcd, 0xd0, 0x3a, 0xb3, 0xce, 0xed, 0x2b, 0xbc,
	0x73, 0x7e, 0xd4, 0x63, 0xcf, 0x07, 0xeb, 0x04, 0x1b, 0x87, 0x04, 0x47, 0xff, 0x0c, 0xb0, 0x8f,
	0xa6, 0x94, 0xf6, 0xe3, 0xfe, 0x4c, 0x6d, 0xca, 0x64, 0x07, 0x42, 0xdd, 0xfd, 0x33, 0x9b, 0x97,
	0x4b, 0xed, 0xca, 0x64, 0x15, 0x50, 0x6f, 0x9e, 0xea, 0x37, 0x55, 0xc0, 0x07, 0x42, 0x65, 0xb0,
	0x94, 0xd9, 0x62, 0x59, 0xe9, 0x9a, 0x6c, 0x87, 0x6a, 0x37, 0xcd, 0xa3, 0xdf, 0xf3, 0x2d, 0xf4,
	0x75, 0x94, 0x51, 0xb1, 0xc9, 0xf4, 0xb6, 0x96, 0x8e, 0xed, 0x39, 0x89, 0xcf, 0xc0, 0x96, 0xf9,
	0xbc, 0x9e, 0x69, 0xeb, 0x99, 0x63, 0xea, 0xe2, 0xaf, 0x09, 0x83, 0xc3, 0x9f, 0x80, 0xe4, 0xdb,
	0x35, 0x3e, 0x05, 0xdb, 0x63, 0xc4, 0x0f, 0x62, 0xe1, 0xb9, 0xcc, 0x47, 0x27, 0x18, 0xa0, 0xe5,
	0xb1, 0xaf, 0x51, 0x1c, 0x22, 0x03, 0xf7, 0xa1, 0xeb, 0xbb, 0x31, 0x11, 0x71, 0x30, 0x25, 0xc8,
	0x54, 0xb3, 0x7e, 0x38, 0x75, 0x03, 0x2a, 0xa8, 0x3b, 0x25, 0xc8, 0xc2, 0x0e, 0xf4, 0xc9, 0xd4,
	0x0d, 0x26, 0xc2, 0xf5, 0x7d, 0x46, 0x38, 0x47, 0x0d, 0xf5, 0x24, 0x18, 0xbb, 0x54, 0x78, 0xa1,
	0x4f, 0x50, 0x13, 0x0f, 0x00, 0x82, 0xa8, 0x6e, 0xb7, 0x70, 0x1b, 0x2c, 0xca, 0x22, 0xd4, 0xc6,
	0x3d, 0xe8, 0x4c, 0x42, 0xcf, 0x8d, 0x83, 0x90, 0xa2, 0x8e, 0x12, 0x8d, 0x08, 0xe3, 0x21, 0x45,
	0x5d, 0x8c, 0xa0, 0x17, 0xdd, 0x84, 0x94, 0x08, 0x9a, 0x4c, 0xc7, 0x84, 0x21, 0xc0, 0x18, 0x06,
	0x09, 0x17, 0x63, 0x97, 0xde, 0xee, 0x39, 0x1b, 0xbf, 0x04, 0x27, 0xe1, 0xc2, 0x67, 0xc1, 0x17,
	0xc2, 0xc4, 0x24, 0xf0, 0x08, 0xe5, 0x04, 0xf5, 0xb0, 0x0d, 0xed, 0x84, 0x8b, 0x20, 0x0e, 0x28,
	0xea, 0x2b, 0xbf, 0x09, 0x17, 0x91, 0xcb, 0x79, 0x14, 0xb2, 0x18, 0x0d, 0x94, 0x4c, 0xc2, 0x05,
	0xe7, 0x14, 0x9d, 0xea, 0xfa, 0x56, 0xd0, 0x1b, 0x8e, 0xd0, 0xc5, 0x27, 0x70, 0x7c, 0x59, 0xca,
	0x99, 0x0a, 0x49, 0x45, 0xa3, 0x93, 0x69, 0x83, 0x15, 0x7a, 0x0c, 0x9d, 0xa8, 0x93, 0xdc, 0x6f,
	0x09, 0x23, 0x42, 0x41, 0x43, 0x9d, 0x54, 0xc1, 0x6b, 0xd7, 0x23, 0xc8, 0xbc, 0x6b, 0xe9, 0x4f,
	0xc0, 0x87, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x25, 0x4b, 0x6d, 0x8b, 0x12, 0x04, 0x00, 0x00,
}
