// Code generated by protoc-gen-go. DO NOT EDIT.
// source: databinder.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DataBinderTypesEnum int32

const (
	DataBinderTypesEnum_mysql         DataBinderTypesEnum = 0
	DataBinderTypesEnum_mssql         DataBinderTypesEnum = 1
	DataBinderTypesEnum_postgres      DataBinderTypesEnum = 2
	DataBinderTypesEnum_sqlite3       DataBinderTypesEnum = 3
	DataBinderTypesEnum_oracle        DataBinderTypesEnum = 4
	DataBinderTypesEnum_kafka         DataBinderTypesEnum = 5
	DataBinderTypesEnum_eventhub      DataBinderTypesEnum = 6
	DataBinderTypesEnum_s3            DataBinderTypesEnum = 7
	DataBinderTypesEnum_azureblob     DataBinderTypesEnum = 8
	DataBinderTypesEnum_googlestorage DataBinderTypesEnum = 9
)

var DataBinderTypesEnum_name = map[int32]string{
	0: "mysql",
	1: "mssql",
	2: "postgres",
	3: "sqlite3",
	4: "oracle",
	5: "kafka",
	6: "eventhub",
	7: "s3",
	8: "azureblob",
	9: "googlestorage",
}
var DataBinderTypesEnum_value = map[string]int32{
	"mysql":         0,
	"mssql":         1,
	"postgres":      2,
	"sqlite3":       3,
	"oracle":        4,
	"kafka":         5,
	"eventhub":      6,
	"s3":            7,
	"azureblob":     8,
	"googlestorage": 9,
}

func (x DataBinderTypesEnum) String() string {
	return proto.EnumName(DataBinderTypesEnum_name, int32(x))
}
func (DataBinderTypesEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_databinder_b6793102677c8d2d, []int{0}
}

// DatabinderRequest represents the request to the data-binder service via GRPC
type DatabinderRequest struct {
	AnalyzeResults       []*AnalyzeResult   `protobuf:"bytes,1,rep,name=analyzeResults,proto3" json:"analyzeResults,omitempty"`
	AnonymizeResult      *AnonymizeResponse `protobuf:"bytes,2,opt,name=anonymizeResult,proto3" json:"anonymizeResult,omitempty"`
	Path                 string             `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DatabinderRequest) Reset()         { *m = DatabinderRequest{} }
func (m *DatabinderRequest) String() string { return proto.CompactTextString(m) }
func (*DatabinderRequest) ProtoMessage()    {}
func (*DatabinderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_databinder_b6793102677c8d2d, []int{0}
}
func (m *DatabinderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabinderRequest.Unmarshal(m, b)
}
func (m *DatabinderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabinderRequest.Marshal(b, m, deterministic)
}
func (dst *DatabinderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabinderRequest.Merge(dst, src)
}
func (m *DatabinderRequest) XXX_Size() int {
	return xxx_messageInfo_DatabinderRequest.Size(m)
}
func (m *DatabinderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabinderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DatabinderRequest proto.InternalMessageInfo

func (m *DatabinderRequest) GetAnalyzeResults() []*AnalyzeResult {
	if m != nil {
		return m.AnalyzeResults
	}
	return nil
}

func (m *DatabinderRequest) GetAnonymizeResult() *AnonymizeResponse {
	if m != nil {
		return m.AnonymizeResult
	}
	return nil
}

func (m *DatabinderRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// DatabinderResponse represents the response from the data-binder service via GRPC
type DatabinderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabinderResponse) Reset()         { *m = DatabinderResponse{} }
func (m *DatabinderResponse) String() string { return proto.CompactTextString(m) }
func (*DatabinderResponse) ProtoMessage()    {}
func (*DatabinderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_databinder_b6793102677c8d2d, []int{1}
}
func (m *DatabinderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabinderResponse.Unmarshal(m, b)
}
func (m *DatabinderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabinderResponse.Marshal(b, m, deterministic)
}
func (dst *DatabinderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabinderResponse.Merge(dst, src)
}
func (m *DatabinderResponse) XXX_Size() int {
	return xxx_messageInfo_DatabinderResponse.Size(m)
}
func (m *DatabinderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabinderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabinderResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DatabinderRequest)(nil), "types.DatabinderRequest")
	proto.RegisterType((*DatabinderResponse)(nil), "types.DatabinderResponse")
	proto.RegisterEnum("types.DataBinderTypesEnum", DataBinderTypesEnum_name, DataBinderTypesEnum_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DatabinderServiceClient is the client API for DatabinderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatabinderServiceClient interface {
	Apply(ctx context.Context, in *DatabinderRequest, opts ...grpc.CallOption) (*DatabinderResponse, error)
	Init(ctx context.Context, in *DatabinderTemplate, opts ...grpc.CallOption) (*DatabinderResponse, error)
}

type databinderServiceClient struct {
	cc *grpc.ClientConn
}

func NewDatabinderServiceClient(cc *grpc.ClientConn) DatabinderServiceClient {
	return &databinderServiceClient{cc}
}

func (c *databinderServiceClient) Apply(ctx context.Context, in *DatabinderRequest, opts ...grpc.CallOption) (*DatabinderResponse, error) {
	out := new(DatabinderResponse)
	err := c.cc.Invoke(ctx, "/types.DatabinderService/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databinderServiceClient) Init(ctx context.Context, in *DatabinderTemplate, opts ...grpc.CallOption) (*DatabinderResponse, error) {
	out := new(DatabinderResponse)
	err := c.cc.Invoke(ctx, "/types.DatabinderService/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabinderServiceServer is the server API for DatabinderService service.
type DatabinderServiceServer interface {
	Apply(context.Context, *DatabinderRequest) (*DatabinderResponse, error)
	Init(context.Context, *DatabinderTemplate) (*DatabinderResponse, error)
}

func RegisterDatabinderServiceServer(s *grpc.Server, srv DatabinderServiceServer) {
	s.RegisterService(&_DatabinderService_serviceDesc, srv)
}

func _DatabinderService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabinderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabinderServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.DatabinderService/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabinderServiceServer).Apply(ctx, req.(*DatabinderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabinderService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabinderTemplate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabinderServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.DatabinderService/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabinderServiceServer).Init(ctx, req.(*DatabinderTemplate))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatabinderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.DatabinderService",
	HandlerType: (*DatabinderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _DatabinderService_Apply_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _DatabinderService_Init_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "databinder.proto",
}

func init() { proto.RegisterFile("databinder.proto", fileDescriptor_databinder_b6793102677c8d2d) }

var fileDescriptor_databinder_b6793102677c8d2d = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4d, 0xee, 0xda, 0x30,
	0x10, 0xc5, 0xff, 0x01, 0x12, 0xc8, 0xf0, 0x51, 0x33, 0x65, 0x91, 0xb2, 0x42, 0xac, 0x50, 0x17,
	0x2c, 0x60, 0x5b, 0x21, 0x81, 0xda, 0x45, 0xb7, 0x29, 0x17, 0x70, 0x60, 0x1a, 0x22, 0x1c, 0xdb,
	0xc4, 0x0e, 0x52, 0xb8, 0x46, 0xd5, 0x43, 0xf4, 0x96, 0x55, 0x12, 0x0a, 0x14, 0xaa, 0xee, 0xc6,
	0x6f, 0xe6, 0xe7, 0x67, 0xbf, 0x01, 0xb6, 0xe7, 0x96, 0x47, 0x89, 0xdc, 0x53, 0x36, 0xd7, 0x99,
	0xb2, 0x0a, 0x5d, 0x5b, 0x68, 0x32, 0xe3, 0xde, 0x4e, 0xa5, 0xa9, 0x92, 0xb5, 0x38, 0x1e, 0x58,
	0x4a, 0xb5, 0xe0, 0x96, 0xae, 0xe7, 0x77, 0x5c, 0x2a, 0x59, 0xa4, 0xc9, 0xe5, 0x2a, 0x4c, 0x7f,
	0x39, 0x30, 0xfc, 0x7c, 0xbb, 0x2a, 0xa4, 0x53, 0x4e, 0xc6, 0xe2, 0x27, 0x18, 0x70, 0xc9, 0x45,
	0x71, 0xa1, 0x90, 0x4c, 0x2e, 0xac, 0x09, 0x9c, 0x49, 0x73, 0xd6, 0x5d, 0x8c, 0xe6, 0x95, 0xc9,
	0x7c, 0xfd, 0xd8, 0x0c, 0x9f, 0x66, 0x71, 0x03, 0x77, 0x9b, 0x5a, 0x0b, 0x1a, 0x13, 0x67, 0xd6,
	0x5d, 0x04, 0x37, 0xfc, 0xde, 0xd5, 0x4a, 0x1a, 0x0a, 0x9f, 0x01, 0x44, 0x68, 0x69, 0x6e, 0x0f,
	0x41, 0x73, 0xe2, 0xcc, 0xfc, 0xb0, 0xaa, 0xa7, 0x23, 0xc0, 0xc7, 0xa7, 0xd6, 0xe8, 0xc7, 0x9f,
	0x0e, 0xbc, 0x2f, 0xe5, 0x4d, 0x25, 0x6f, 0x4b, 0x83, 0x2f, 0x32, 0x4f, 0xd1, 0x07, 0x37, 0x2d,
	0xcc, 0x49, 0xb0, 0xb7, 0xaa, 0x34, 0x65, 0xe9, 0x60, 0x0f, 0x3a, 0x5a, 0x19, 0x1b, 0x67, 0x64,
	0x58, 0x03, 0xbb, 0xd0, 0x36, 0x27, 0x91, 0x58, 0x5a, 0xb2, 0x26, 0x02, 0x78, 0x2a, 0xe3, 0x3b,
	0x41, 0xac, 0x55, 0x12, 0x47, 0xfe, 0xfd, 0xc8, 0x99, 0x5b, 0x12, 0x74, 0x26, 0x69, 0x0f, 0x79,
	0xc4, 0x3c, 0xf4, 0xa0, 0x61, 0x96, 0xac, 0x8d, 0x7d, 0xf0, 0xf9, 0x25, 0xcf, 0x28, 0x12, 0x2a,
	0x62, 0x1d, 0x1c, 0x42, 0x3f, 0x56, 0x2a, 0x16, 0x64, 0xac, 0xca, 0x78, 0x4c, 0xcc, 0x5f, 0xfc,
	0xf8, 0x2b, 0xd9, 0x6f, 0x94, 0x9d, 0x93, 0x1d, 0xe1, 0x0a, 0xdc, 0xb5, 0xd6, 0xa2, 0xc0, 0x3f,
	0x59, 0xbc, 0x84, 0x3f, 0xfe, 0xf0, 0x8f, 0x4e, 0xfd, 0xd7, 0xe9, 0x1b, 0xae, 0xa0, 0xf5, 0x55,
	0x26, 0x16, 0x5f, 0x87, 0xb6, 0xd7, 0x4d, 0xff, 0x97, 0x8f, 0xbc, 0x6a, 0xed, 0xcb, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x81, 0x12, 0x38, 0xf2, 0x40, 0x02, 0x00, 0x00,
}
