// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Job struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string             `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Trigger              *Trigger           `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	AnalyzeTemplate      *AnalyzeTemplate   `protobuf:"bytes,4,opt,name=analyzeTemplate,proto3" json:"analyzeTemplate,omitempty"`
	AnonymizeTemplate    *AnonymizeTemplate `protobuf:"bytes,5,opt,name=anonymizeTemplate,proto3" json:"anonymizeTemplate,omitempty"`
	ScannerTemplate      *ScannerTemplate   `protobuf:"bytes,6,opt,name=scannerTemplate,proto3" json:"scannerTemplate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_4e6caaf8b94b1b94, []int{0}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetTrigger() *Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

func (m *Job) GetAnalyzeTemplate() *AnalyzeTemplate {
	if m != nil {
		return m.AnalyzeTemplate
	}
	return nil
}

func (m *Job) GetAnonymizeTemplate() *AnonymizeTemplate {
	if m != nil {
		return m.AnonymizeTemplate
	}
	return nil
}

func (m *Job) GetScannerTemplate() *ScannerTemplate {
	if m != nil {
		return m.ScannerTemplate
	}
	return nil
}

type Trigger struct {
	Schedule             *Schedule `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Trigger) Reset()         { *m = Trigger{} }
func (m *Trigger) String() string { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()    {}
func (*Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_4e6caaf8b94b1b94, []int{1}
}
func (m *Trigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trigger.Unmarshal(m, b)
}
func (m *Trigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trigger.Marshal(b, m, deterministic)
}
func (dst *Trigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trigger.Merge(dst, src)
}
func (m *Trigger) XXX_Size() int {
	return xxx_messageInfo_Trigger.Size(m)
}
func (m *Trigger) XXX_DiscardUnknown() {
	xxx_messageInfo_Trigger.DiscardUnknown(m)
}

var xxx_messageInfo_Trigger proto.InternalMessageInfo

func (m *Trigger) GetSchedule() *Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

type Schedule struct {
	RecurrencePeriodDuration string   `protobuf:"bytes,1,opt,name=recurrencePeriodDuration,proto3" json:"recurrencePeriodDuration,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_4e6caaf8b94b1b94, []int{2}
}
func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (dst *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(dst, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetRecurrencePeriodDuration() string {
	if m != nil {
		return m.RecurrencePeriodDuration
	}
	return ""
}

func init() {
	proto.RegisterType((*Job)(nil), "types.Job")
	proto.RegisterType((*Trigger)(nil), "types.Trigger")
	proto.RegisterType((*Schedule)(nil), "types.Schedule")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_job_4e6caaf8b94b1b94) }

var fileDescriptor_job_4e6caaf8b94b1b94 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x6a, 0xb4, 0x30,
	0x14, 0xc5, 0x71, 0xfe, 0xcf, 0x15, 0x66, 0xf8, 0xb2, 0xf8, 0x08, 0x5d, 0x89, 0x2b, 0xa1, 0xe0,
	0x62, 0x0a, 0x5d, 0x74, 0xd5, 0x42, 0x99, 0x45, 0x57, 0x25, 0x9d, 0x17, 0x88, 0x7a, 0x99, 0xa6,
	0x68, 0x22, 0xd7, 0xb8, 0xb0, 0x6f, 0xd5, 0x37, 0x2c, 0x4d, 0x1c, 0x19, 0x2d, 0xdd, 0xc9, 0xf9,
	0xdd, 0x73, 0x3c, 0xb9, 0x17, 0xb6, 0x1f, 0x26, 0x4b, 0x6b, 0x32, 0xd6, 0xb0, 0xa5, 0xed, 0x6a,
	0x6c, 0x6e, 0x76, 0x16, 0xab, 0xba, 0x94, 0x16, 0xbd, 0x1c, 0x7f, 0xcd, 0x60, 0xfe, 0x62, 0x32,
	0xc6, 0x60, 0xa1, 0x65, 0x85, 0x3c, 0x88, 0x82, 0x64, 0x2b, 0xdc, 0x37, 0x8b, 0x20, 0x2c, 0xb0,
	0xc9, 0x49, 0xd5, 0x56, 0x19, 0xcd, 0x67, 0x0e, 0x5d, 0x4b, 0x2c, 0x81, 0xb5, 0x25, 0x75, 0x3e,
	0x23, 0xf1, 0x79, 0x14, 0x24, 0xe1, 0x61, 0x97, 0xba, 0xdf, 0xa4, 0x27, 0xaf, 0x8a, 0x0b, 0x66,
	0x8f, 0xb0, 0x97, 0x5a, 0x96, 0xdd, 0x27, 0x9e, 0xfa, 0x02, 0x7c, 0xe1, 0x1c, 0xff, 0x7b, 0xc7,
	0xd3, 0x98, 0x8a, 0xe9, 0x38, 0x3b, 0xc2, 0x3f, 0xa9, 0x8d, 0xee, 0x2a, 0x75, 0x95, 0xb1, 0x74,
	0x19, 0x7c, 0xc8, 0x98, 0x70, 0xf1, 0xdb, 0xf2, 0xd3, 0xa4, 0xc9, 0xa5, 0xd6, 0x48, 0x43, 0xca,
	0x6a, 0xd4, 0xe4, 0x6d, 0x4c, 0xc5, 0x74, 0x3c, 0xbe, 0x87, 0x75, 0xff, 0x3e, 0x76, 0x0b, 0x9b,
	0x26, 0x7f, 0xc7, 0xa2, 0x2d, 0xfd, 0xea, 0xc2, 0xc3, 0x7e, 0x48, 0xf1, 0xb2, 0x18, 0x06, 0xe2,
	0x23, 0x6c, 0x2e, 0x2a, 0x7b, 0x00, 0x4e, 0x98, 0xb7, 0x44, 0xa8, 0x73, 0x7c, 0x45, 0x52, 0xa6,
	0x78, 0x6e, 0x49, 0xba, 0x45, 0xfb, 0x1b, 0xfc, 0xc9, 0xb3, 0x95, 0x3b, 0xdd, 0xdd, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xdc, 0x41, 0x51, 0x22, 0xde, 0x01, 0x00, 0x00,
}
