// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scan.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ScanRequest represents the request to the scanner service via GRPC
type ScanRequest struct {
	// The scanTemplate configures the input source of the scanning
	ScanTemplate *ScanTemplate `protobuf:"bytes,1,opt,name=scanTemplate,proto3" json:"scanTemplate,omitempty"`
	// The analyzer template configures the fields to analyze
	AnalyzeTemplate *AnalyzeTemplate `protobuf:"bytes,2,opt,name=analyzeTemplate,proto3" json:"analyzeTemplate,omitempty"`
	// The anonymizer template configures how to anonymize the sensitive data [optional]
	AnonymizeTemplate *AnonymizeTemplate `protobuf:"bytes,3,opt,name=anonymizeTemplate,proto3" json:"anonymizeTemplate,omitempty"`
	// The datasinkTemplate configures the output destination of the analyzer/anonymizer results
	DatasinkTemplate     *DatasinkTemplate `protobuf:"bytes,4,opt,name=datasinkTemplate,proto3" json:"datasinkTemplate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_scan_f81eff17dada0630, []int{0}
}
func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (dst *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(dst, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetScanTemplate() *ScanTemplate {
	if m != nil {
		return m.ScanTemplate
	}
	return nil
}

func (m *ScanRequest) GetAnalyzeTemplate() *AnalyzeTemplate {
	if m != nil {
		return m.AnalyzeTemplate
	}
	return nil
}

func (m *ScanRequest) GetAnonymizeTemplate() *AnonymizeTemplate {
	if m != nil {
		return m.AnonymizeTemplate
	}
	return nil
}

func (m *ScanRequest) GetDatasinkTemplate() *DatasinkTemplate {
	if m != nil {
		return m.DatasinkTemplate
	}
	return nil
}

func init() {
	proto.RegisterType((*ScanRequest)(nil), "types.ScanRequest")
}

func init() { proto.RegisterFile("scan.proto", fileDescriptor_scan_f81eff17dada0630) }

var fileDescriptor_scan_f81eff17dada0630 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x4e, 0x4e, 0xcc,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xa9, 0x2c, 0x48, 0x2d, 0x96, 0xe2, 0x2b,
	0x49, 0xcd, 0x2d, 0xc8, 0x49, 0x2c, 0x49, 0x85, 0x08, 0x2b, 0x4d, 0x65, 0xe2, 0xe2, 0x0e, 0x06,
	0xaa, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x32, 0xe7, 0xe2, 0x01, 0x69, 0x0a, 0x81,
	0xaa, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0x12, 0xd6, 0x03, 0xeb, 0xd6, 0x0b, 0x46, 0x92,
	0x0a, 0x42, 0x51, 0x28, 0xe4, 0xc0, 0xc5, 0x9f, 0x98, 0x97, 0x98, 0x53, 0x59, 0x95, 0x0a, 0xd7,
	0xcb, 0x04, 0xd6, 0x2b, 0x06, 0xd5, 0xeb, 0x88, 0x2a, 0x1b, 0x84, 0xae, 0x5c, 0xc8, 0x8d, 0x4b,
	0x30, 0x31, 0x2f, 0x3f, 0xaf, 0x32, 0x37, 0x13, 0xc9, 0x0c, 0x66, 0xb0, 0x19, 0x12, 0x70, 0x33,
	0xd0, 0xe4, 0x83, 0x30, 0xb5, 0x08, 0x39, 0x73, 0x09, 0xa4, 0x24, 0x96, 0x24, 0x16, 0x67, 0xe6,
	0x65, 0xc3, 0x8d, 0x61, 0x01, 0x1b, 0x23, 0x0e, 0x35, 0xc6, 0x05, 0x4d, 0x3a, 0x08, 0x43, 0x43,
	0x12, 0x1b, 0x38, 0x78, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xa1, 0x00, 0x59, 0x43,
	0x01, 0x00, 0x00,
}
