// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scan.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ScanRequest struct {
	Kind                 string              `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	CloudStorageConfig   *CloudStorageConfig `protobuf:"bytes,2,opt,name=cloudStorageConfig,proto3" json:"cloudStorageConfig,omitempty"`
	MinProbability       string              `protobuf:"bytes,3,opt,name=minProbability,proto3" json:"minProbability,omitempty"`
	AnalyzeTemplate      *AnalyzeTemplate    `protobuf:"bytes,4,opt,name=analyzeTemplate,proto3" json:"analyzeTemplate,omitempty"`
	AnonymizeTemplate    *AnonymizeTemplate  `protobuf:"bytes,5,opt,name=anonymizeTemplate,proto3" json:"anonymizeTemplate,omitempty"`
	DataSyncTemplate     *DataSyncTemplate   `protobuf:"bytes,6,opt,name=dataSyncTemplate,proto3" json:"dataSyncTemplate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_scan_bc4418995ca4aaa3, []int{0}
}
func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (dst *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(dst, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ScanRequest) GetCloudStorageConfig() *CloudStorageConfig {
	if m != nil {
		return m.CloudStorageConfig
	}
	return nil
}

func (m *ScanRequest) GetMinProbability() string {
	if m != nil {
		return m.MinProbability
	}
	return ""
}

func (m *ScanRequest) GetAnalyzeTemplate() *AnalyzeTemplate {
	if m != nil {
		return m.AnalyzeTemplate
	}
	return nil
}

func (m *ScanRequest) GetAnonymizeTemplate() *AnonymizeTemplate {
	if m != nil {
		return m.AnonymizeTemplate
	}
	return nil
}

func (m *ScanRequest) GetDataSyncTemplate() *DataSyncTemplate {
	if m != nil {
		return m.DataSyncTemplate
	}
	return nil
}

func init() {
	proto.RegisterType((*ScanRequest)(nil), "types.ScanRequest")
}

func init() { proto.RegisterFile("scan.proto", fileDescriptor_scan_bc4418995ca4aaa3) }

var fileDescriptor_scan_bc4418995ca4aaa3 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x6d, 0x0b, 0x4e, 0xa1, 0xea, 0x1c, 0x74, 0xf5, 0x54, 0x3c, 0x48, 0x4f, 0x39,
	0xe8, 0x0b, 0x28, 0x11, 0xc1, 0x9b, 0x6c, 0x7c, 0x81, 0x49, 0xb2, 0x96, 0xc5, 0xcd, 0x6c, 0x4c,
	0xa6, 0x87, 0xf5, 0x75, 0x7d, 0x11, 0x61, 0x0d, 0x45, 0x37, 0xde, 0x96, 0xef, 0xcf, 0xef, 0x5b,
	0x06, 0x60, 0xa8, 0x89, 0xf3, 0xae, 0xf7, 0xe2, 0x71, 0x21, 0xa1, 0x33, 0xc3, 0xd5, 0x5a, 0x4c,
	0xdb, 0x39, 0x12, 0xf3, 0x23, 0x5f, 0x7f, 0xcd, 0x60, 0x55, 0xd6, 0xc4, 0xda, 0x7c, 0xec, 0xcd,
	0x20, 0x88, 0x30, 0x7f, 0xb7, 0xdc, 0xa8, 0x6c, 0x93, 0x6d, 0x8f, 0x75, 0x7c, 0xe3, 0x33, 0x60,
	0xed, 0xfc, 0xbe, 0x29, 0xc5, 0xf7, 0xb4, 0x33, 0x85, 0xe7, 0x37, 0xbb, 0x53, 0xb3, 0x4d, 0xb6,
	0x5d, 0xdd, 0x5e, 0xe6, 0x91, 0x9b, 0x17, 0x93, 0x80, 0xfe, 0xa7, 0x84, 0x37, 0xb0, 0x6e, 0x2d,
	0xbf, 0xf4, 0xbe, 0xa2, 0xca, 0x3a, 0x2b, 0x41, 0x1d, 0xc5, 0xa1, 0x44, 0xc5, 0x7b, 0x38, 0x21,
	0x26, 0x17, 0x3e, 0xcd, 0xeb, 0xf8, 0x5f, 0x35, 0x8f, 0x7b, 0xe7, 0xe3, 0xde, 0xc3, 0x5f, 0x57,
	0xa7, 0x71, 0x7c, 0x82, 0x33, 0x62, 0xcf, 0xa1, 0xb5, 0xbf, 0x18, 0x8b, 0xc8, 0x50, 0x07, 0x46,
	0xe2, 0xeb, 0x69, 0x05, 0x0b, 0x38, 0x6d, 0x48, 0xa8, 0x0c, 0x5c, 0x1f, 0x30, 0xcb, 0x88, 0xb9,
	0x18, 0x31, 0x8f, 0x89, 0xad, 0x27, 0x85, 0x6a, 0x19, 0x8f, 0x7d, 0xf7, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0xe9, 0x91, 0xa4, 0xcb, 0x91, 0x01, 0x00, 0x00,
}
