// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StreamRequest struct {
	Kind                 string              `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
	InputConfig          *StreamConfig       `protobuf:"bytes,2,opt,name=inputConfig" json:"inputConfig,omitempty"`
	MinProbability       string              `protobuf:"bytes,3,opt,name=minProbability" json:"minProbability,omitempty"`
	AnalyzeTemplate      *AnalyzeTemplate    `protobuf:"bytes,4,opt,name=analyzeTemplate" json:"analyzeTemplate,omitempty"`
	AnonymizeTemplate    *AnonymizeTemplate  `protobuf:"bytes,5,opt,name=anonymizeTemplate" json:"anonymizeTemplate,omitempty"`
	DatabinderTemplate   *DatabinderTemplate `protobuf:"bytes,6,opt,name=databinderTemplate" json:"databinderTemplate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_1f360b43d23f51a2, []int{0}
}
func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (dst *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(dst, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *StreamRequest) GetInputConfig() *StreamConfig {
	if m != nil {
		return m.InputConfig
	}
	return nil
}

func (m *StreamRequest) GetMinProbability() string {
	if m != nil {
		return m.MinProbability
	}
	return ""
}

func (m *StreamRequest) GetAnalyzeTemplate() *AnalyzeTemplate {
	if m != nil {
		return m.AnalyzeTemplate
	}
	return nil
}

func (m *StreamRequest) GetAnonymizeTemplate() *AnonymizeTemplate {
	if m != nil {
		return m.AnonymizeTemplate
	}
	return nil
}

func (m *StreamRequest) GetDatabinderTemplate() *DatabinderTemplate {
	if m != nil {
		return m.DatabinderTemplate
	}
	return nil
}

func init() {
	proto.RegisterType((*StreamRequest)(nil), "types.StreamRequest")
}

func init() { proto.RegisterFile("stream.proto", fileDescriptor_stream_1f360b43d23f51a2) }

var fileDescriptor_stream_1f360b43d23f51a2 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x6d, 0x0b, 0x6e, 0xb5, 0xe2, 0x08, 0xb2, 0x7a, 0x2a, 0x1e, 0xa4, 0xa7, 0x1c,
	0x14, 0xef, 0x8a, 0x22, 0x78, 0x93, 0xd5, 0x17, 0x98, 0x90, 0x51, 0x06, 0x93, 0xd9, 0x98, 0x4c,
	0x0f, 0xf1, 0x45, 0x7d, 0x1d, 0x61, 0x12, 0x4a, 0x4d, 0x7a, 0x5b, 0xe6, 0xff, 0xfe, 0x6f, 0x96,
	0x71, 0x47, 0x8d, 0xd6, 0x84, 0x65, 0x5a, 0xd5, 0x51, 0x23, 0xcc, 0xb4, 0xad, 0xa8, 0xb9, 0x5c,
	0x2a, 0x95, 0x55, 0x81, 0x4a, 0xdd, 0xf8, 0xea, 0x77, 0xe2, 0x8e, 0xdf, 0x8c, 0x0b, 0xf4, 0xbd,
	0xa1, 0x46, 0x01, 0xdc, 0xf4, 0x8b, 0x25, 0xf7, 0xc9, 0x2a, 0x59, 0x1f, 0x06, 0x7b, 0xc3, 0x9d,
	0x5b, 0xb0, 0x54, 0x1b, 0x7d, 0x8c, 0xf2, 0xc1, 0x9f, 0x7e, 0xb2, 0x4a, 0xd6, 0x8b, 0x9b, 0xb3,
	0xd4, 0x94, 0x69, 0x57, 0xef, 0xa2, 0xb0, 0xcb, 0xc1, 0xb5, 0x5b, 0x96, 0x2c, 0xaf, 0x75, 0xcc,
	0x30, 0xe3, 0x82, 0xb5, 0xf5, 0x07, 0x26, 0x1d, 0x4c, 0xe1, 0xde, 0x9d, 0xa0, 0x60, 0xd1, 0xfe,
	0xd0, 0x7b, 0xff, 0x3b, 0x3f, 0xb5, 0x15, 0xe7, 0xfd, 0x8a, 0x87, 0xff, 0x69, 0x18, 0xe2, 0xf0,
	0xec, 0x4e, 0x51, 0xa2, 0xb4, 0x25, 0xef, 0x38, 0x66, 0xe6, 0xf0, 0x5b, 0xc7, 0x20, 0x0f, 0xe3,
	0x0a, 0xbc, 0x38, 0xc8, 0x51, 0x31, 0x63, 0xc9, 0xa9, 0xde, 0x8a, 0xe6, 0x26, 0xba, 0xe8, 0x45,
	0x4f, 0x23, 0x20, 0xec, 0x29, 0x65, 0x73, 0x3b, 0xf0, 0xed, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x4b, 0x41, 0x09, 0xbf, 0x87, 0x01, 0x00, 0x00,
}
