// Code generated by protoc-gen-go. DO NOT EDIT.
// source: template.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AnalyzeTemplate represents the analyze service template definition
type AnalyzeTemplate struct {
	Fields               []*FieldTypes `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AnalyzeTemplate) Reset()         { *m = AnalyzeTemplate{} }
func (m *AnalyzeTemplate) String() string { return proto.CompactTextString(m) }
func (*AnalyzeTemplate) ProtoMessage()    {}
func (*AnalyzeTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_dc82fa9fe15cb310, []int{0}
}
func (m *AnalyzeTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeTemplate.Unmarshal(m, b)
}
func (m *AnalyzeTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeTemplate.Marshal(b, m, deterministic)
}
func (dst *AnalyzeTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeTemplate.Merge(dst, src)
}
func (m *AnalyzeTemplate) XXX_Size() int {
	return xxx_messageInfo_AnalyzeTemplate.Size(m)
}
func (m *AnalyzeTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeTemplate proto.InternalMessageInfo

func (m *AnalyzeTemplate) GetFields() []*FieldTypes {
	if m != nil {
		return m.Fields
	}
	return nil
}

// AnonymizeTemplate represents the anonymize service template definition
type AnonymizeTemplate struct {
	Name                     string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName              string                     `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Description              string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreateTime               string                     `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	ModifiedTime             string                     `protobuf:"bytes,5,opt,name=modifiedTime,proto3" json:"modifiedTime,omitempty"`
	FieldTypeTransformations []*FieldTypeTransformation `protobuf:"bytes,6,rep,name=fieldTypeTransformations,proto3" json:"fieldTypeTransformations,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                   `json:"-"`
	XXX_unrecognized         []byte                     `json:"-"`
	XXX_sizecache            int32                      `json:"-"`
}

func (m *AnonymizeTemplate) Reset()         { *m = AnonymizeTemplate{} }
func (m *AnonymizeTemplate) String() string { return proto.CompactTextString(m) }
func (*AnonymizeTemplate) ProtoMessage()    {}
func (*AnonymizeTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_dc82fa9fe15cb310, []int{1}
}
func (m *AnonymizeTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnonymizeTemplate.Unmarshal(m, b)
}
func (m *AnonymizeTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnonymizeTemplate.Marshal(b, m, deterministic)
}
func (dst *AnonymizeTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnonymizeTemplate.Merge(dst, src)
}
func (m *AnonymizeTemplate) XXX_Size() int {
	return xxx_messageInfo_AnonymizeTemplate.Size(m)
}
func (m *AnonymizeTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_AnonymizeTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_AnonymizeTemplate proto.InternalMessageInfo

func (m *AnonymizeTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnonymizeTemplate) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *AnonymizeTemplate) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AnonymizeTemplate) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *AnonymizeTemplate) GetModifiedTime() string {
	if m != nil {
		return m.ModifiedTime
	}
	return ""
}

func (m *AnonymizeTemplate) GetFieldTypeTransformations() []*FieldTypeTransformation {
	if m != nil {
		return m.FieldTypeTransformations
	}
	return nil
}

// FieldTypeTransformation represents the transformation for array of fields types
type FieldTypeTransformation struct {
	Fields               []*FieldTypes   `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Transformation       *Transformation `protobuf:"bytes,2,opt,name=transformation,proto3" json:"transformation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FieldTypeTransformation) Reset()         { *m = FieldTypeTransformation{} }
func (m *FieldTypeTransformation) String() string { return proto.CompactTextString(m) }
func (*FieldTypeTransformation) ProtoMessage()    {}
func (*FieldTypeTransformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_dc82fa9fe15cb310, []int{2}
}
func (m *FieldTypeTransformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldTypeTransformation.Unmarshal(m, b)
}
func (m *FieldTypeTransformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldTypeTransformation.Marshal(b, m, deterministic)
}
func (dst *FieldTypeTransformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldTypeTransformation.Merge(dst, src)
}
func (m *FieldTypeTransformation) XXX_Size() int {
	return xxx_messageInfo_FieldTypeTransformation.Size(m)
}
func (m *FieldTypeTransformation) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldTypeTransformation.DiscardUnknown(m)
}

var xxx_messageInfo_FieldTypeTransformation proto.InternalMessageInfo

func (m *FieldTypeTransformation) GetFields() []*FieldTypes {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *FieldTypeTransformation) GetTransformation() *Transformation {
	if m != nil {
		return m.Transformation
	}
	return nil
}

// Transformation represents the transformation type
type Transformation struct {
	NewValue             string        `protobuf:"bytes,1,opt,name=newValue,proto3" json:"newValue,omitempty"`
	ReplaceValue         *ReplaceValue `protobuf:"bytes,2,opt,name=replaceValue,proto3" json:"replaceValue,omitempty"`
	RedactValue          *RedactValue  `protobuf:"bytes,3,opt,name=redactValue,proto3" json:"redactValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Transformation) Reset()         { *m = Transformation{} }
func (m *Transformation) String() string { return proto.CompactTextString(m) }
func (*Transformation) ProtoMessage()    {}
func (*Transformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_dc82fa9fe15cb310, []int{3}
}
func (m *Transformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transformation.Unmarshal(m, b)
}
func (m *Transformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transformation.Marshal(b, m, deterministic)
}
func (dst *Transformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transformation.Merge(dst, src)
}
func (m *Transformation) XXX_Size() int {
	return xxx_messageInfo_Transformation.Size(m)
}
func (m *Transformation) XXX_DiscardUnknown() {
	xxx_messageInfo_Transformation.DiscardUnknown(m)
}

var xxx_messageInfo_Transformation proto.InternalMessageInfo

func (m *Transformation) GetNewValue() string {
	if m != nil {
		return m.NewValue
	}
	return ""
}

func (m *Transformation) GetReplaceValue() *ReplaceValue {
	if m != nil {
		return m.ReplaceValue
	}
	return nil
}

func (m *Transformation) GetRedactValue() *RedactValue {
	if m != nil {
		return m.RedactValue
	}
	return nil
}

type ReplaceValue struct {
	NewValue             string   `protobuf:"bytes,1,opt,name=newValue,proto3" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplaceValue) Reset()         { *m = ReplaceValue{} }
func (m *ReplaceValue) String() string { return proto.CompactTextString(m) }
func (*ReplaceValue) ProtoMessage()    {}
func (*ReplaceValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_dc82fa9fe15cb310, []int{4}
}
func (m *ReplaceValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceValue.Unmarshal(m, b)
}
func (m *ReplaceValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceValue.Marshal(b, m, deterministic)
}
func (dst *ReplaceValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceValue.Merge(dst, src)
}
func (m *ReplaceValue) XXX_Size() int {
	return xxx_messageInfo_ReplaceValue.Size(m)
}
func (m *ReplaceValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceValue.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceValue proto.InternalMessageInfo

func (m *ReplaceValue) GetNewValue() string {
	if m != nil {
		return m.NewValue
	}
	return ""
}

type RedactValue struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedactValue) Reset()         { *m = RedactValue{} }
func (m *RedactValue) String() string { return proto.CompactTextString(m) }
func (*RedactValue) ProtoMessage()    {}
func (*RedactValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_dc82fa9fe15cb310, []int{5}
}
func (m *RedactValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedactValue.Unmarshal(m, b)
}
func (m *RedactValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedactValue.Marshal(b, m, deterministic)
}
func (dst *RedactValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedactValue.Merge(dst, src)
}
func (m *RedactValue) XXX_Size() int {
	return xxx_messageInfo_RedactValue.Size(m)
}
func (m *RedactValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RedactValue.DiscardUnknown(m)
}

var xxx_messageInfo_RedactValue proto.InternalMessageInfo

type Databinder struct {
	BindType             string   `protobuf:"bytes,1,opt,name=bindType,proto3" json:"bindType,omitempty"`
	ConnectionString     string   `protobuf:"bytes,2,opt,name=connectionString,proto3" json:"connectionString,omitempty"`
	TableName            string   `protobuf:"bytes,3,opt,name=tableName,proto3" json:"tableName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Databinder) Reset()         { *m = Databinder{} }
func (m *Databinder) String() string { return proto.CompactTextString(m) }
func (*Databinder) ProtoMessage()    {}
func (*Databinder) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_dc82fa9fe15cb310, []int{6}
}
func (m *Databinder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Databinder.Unmarshal(m, b)
}
func (m *Databinder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Databinder.Marshal(b, m, deterministic)
}
func (dst *Databinder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Databinder.Merge(dst, src)
}
func (m *Databinder) XXX_Size() int {
	return xxx_messageInfo_Databinder.Size(m)
}
func (m *Databinder) XXX_DiscardUnknown() {
	xxx_messageInfo_Databinder.DiscardUnknown(m)
}

var xxx_messageInfo_Databinder proto.InternalMessageInfo

func (m *Databinder) GetBindType() string {
	if m != nil {
		return m.BindType
	}
	return ""
}

func (m *Databinder) GetConnectionString() string {
	if m != nil {
		return m.ConnectionString
	}
	return ""
}

func (m *Databinder) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

// DatabinderTemplate represents the analyzer service outputs definition
type DatabinderTemplate struct {
	Databinder           []*Databinder `protobuf:"bytes,1,rep,name=databinder,proto3" json:"databinder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DatabinderTemplate) Reset()         { *m = DatabinderTemplate{} }
func (m *DatabinderTemplate) String() string { return proto.CompactTextString(m) }
func (*DatabinderTemplate) ProtoMessage()    {}
func (*DatabinderTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_dc82fa9fe15cb310, []int{7}
}
func (m *DatabinderTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabinderTemplate.Unmarshal(m, b)
}
func (m *DatabinderTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabinderTemplate.Marshal(b, m, deterministic)
}
func (dst *DatabinderTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabinderTemplate.Merge(dst, src)
}
func (m *DatabinderTemplate) XXX_Size() int {
	return xxx_messageInfo_DatabinderTemplate.Size(m)
}
func (m *DatabinderTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabinderTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_DatabinderTemplate proto.InternalMessageInfo

func (m *DatabinderTemplate) GetDatabinder() []*Databinder {
	if m != nil {
		return m.Databinder
	}
	return nil
}

type BlobStorageConnector struct {
	AccountName          string   `protobuf:"bytes,1,opt,name=accountName,proto3" json:"accountName,omitempty"`
	AccountKey           string   `protobuf:"bytes,2,opt,name=accountKey,proto3" json:"accountKey,omitempty"`
	ContainrName         string   `protobuf:"bytes,3,opt,name=containrName,proto3" json:"containrName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlobStorageConnector) Reset()         { *m = BlobStorageConnector{} }
func (m *BlobStorageConnector) String() string { return proto.CompactTextString(m) }
func (*BlobStorageConnector) ProtoMessage()    {}
func (*BlobStorageConnector) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_dc82fa9fe15cb310, []int{8}
}
func (m *BlobStorageConnector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobStorageConnector.Unmarshal(m, b)
}
func (m *BlobStorageConnector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobStorageConnector.Marshal(b, m, deterministic)
}
func (dst *BlobStorageConnector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobStorageConnector.Merge(dst, src)
}
func (m *BlobStorageConnector) XXX_Size() int {
	return xxx_messageInfo_BlobStorageConnector.Size(m)
}
func (m *BlobStorageConnector) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobStorageConnector.DiscardUnknown(m)
}

var xxx_messageInfo_BlobStorageConnector proto.InternalMessageInfo

func (m *BlobStorageConnector) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *BlobStorageConnector) GetAccountKey() string {
	if m != nil {
		return m.AccountKey
	}
	return ""
}

func (m *BlobStorageConnector) GetContainrName() string {
	if m != nil {
		return m.ContainrName
	}
	return ""
}

type S3Connector struct {
	AccessId             string   `protobuf:"bytes,1,opt,name=accessId,proto3" json:"accessId,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	BucketName           string   `protobuf:"bytes,3,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S3Connector) Reset()         { *m = S3Connector{} }
func (m *S3Connector) String() string { return proto.CompactTextString(m) }
func (*S3Connector) ProtoMessage()    {}
func (*S3Connector) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_dc82fa9fe15cb310, []int{9}
}
func (m *S3Connector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3Connector.Unmarshal(m, b)
}
func (m *S3Connector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3Connector.Marshal(b, m, deterministic)
}
func (dst *S3Connector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3Connector.Merge(dst, src)
}
func (m *S3Connector) XXX_Size() int {
	return xxx_messageInfo_S3Connector.Size(m)
}
func (m *S3Connector) XXX_DiscardUnknown() {
	xxx_messageInfo_S3Connector.DiscardUnknown(m)
}

var xxx_messageInfo_S3Connector proto.InternalMessageInfo

func (m *S3Connector) GetAccessId() string {
	if m != nil {
		return m.AccessId
	}
	return ""
}

func (m *S3Connector) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *S3Connector) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

type ScannerTemplate struct {
	Kind                 string                `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	BlobStorageConnector *BlobStorageConnector `protobuf:"bytes,2,opt,name=blobStorageConnector,proto3" json:"blobStorageConnector,omitempty"`
	S3Connector          *S3Connector          `protobuf:"bytes,3,opt,name=s3Connector,proto3" json:"s3Connector,omitempty"`
	DatabinderTemplate   *DatabinderTemplate   `protobuf:"bytes,4,opt,name=databinderTemplate,proto3" json:"databinderTemplate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ScannerTemplate) Reset()         { *m = ScannerTemplate{} }
func (m *ScannerTemplate) String() string { return proto.CompactTextString(m) }
func (*ScannerTemplate) ProtoMessage()    {}
func (*ScannerTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_dc82fa9fe15cb310, []int{10}
}
func (m *ScannerTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScannerTemplate.Unmarshal(m, b)
}
func (m *ScannerTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScannerTemplate.Marshal(b, m, deterministic)
}
func (dst *ScannerTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScannerTemplate.Merge(dst, src)
}
func (m *ScannerTemplate) XXX_Size() int {
	return xxx_messageInfo_ScannerTemplate.Size(m)
}
func (m *ScannerTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_ScannerTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_ScannerTemplate proto.InternalMessageInfo

func (m *ScannerTemplate) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ScannerTemplate) GetBlobStorageConnector() *BlobStorageConnector {
	if m != nil {
		return m.BlobStorageConnector
	}
	return nil
}

func (m *ScannerTemplate) GetS3Connector() *S3Connector {
	if m != nil {
		return m.S3Connector
	}
	return nil
}

func (m *ScannerTemplate) GetDatabinderTemplate() *DatabinderTemplate {
	if m != nil {
		return m.DatabinderTemplate
	}
	return nil
}

func init() {
	proto.RegisterType((*AnalyzeTemplate)(nil), "types.AnalyzeTemplate")
	proto.RegisterType((*AnonymizeTemplate)(nil), "types.AnonymizeTemplate")
	proto.RegisterType((*FieldTypeTransformation)(nil), "types.FieldTypeTransformation")
	proto.RegisterType((*Transformation)(nil), "types.Transformation")
	proto.RegisterType((*ReplaceValue)(nil), "types.ReplaceValue")
	proto.RegisterType((*RedactValue)(nil), "types.RedactValue")
	proto.RegisterType((*Databinder)(nil), "types.Databinder")
	proto.RegisterType((*DatabinderTemplate)(nil), "types.DatabinderTemplate")
	proto.RegisterType((*BlobStorageConnector)(nil), "types.BlobStorageConnector")
	proto.RegisterType((*S3Connector)(nil), "types.S3Connector")
	proto.RegisterType((*ScannerTemplate)(nil), "types.ScannerTemplate")
}

func init() { proto.RegisterFile("template.proto", fileDescriptor_template_dc82fa9fe15cb310) }

var fileDescriptor_template_dc82fa9fe15cb310 = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x56, 0xf6, 0xa3, 0xda, 0x5e, 0xca, 0xc6, 0xcc, 0x80, 0x50, 0xd0, 0x54, 0xf9, 0x34, 0x76,
	0xa8, 0x44, 0x87, 0xc4, 0x05, 0x0e, 0x03, 0x04, 0x9a, 0x90, 0x86, 0x94, 0x56, 0x1c, 0xb8, 0x39,
	0xce, 0x6b, 0x65, 0x2d, 0xb1, 0x23, 0xc7, 0x15, 0x2a, 0xe2, 0xc6, 0x91, 0x3f, 0x81, 0x3f, 0x94,
	0x2b, 0xb2, 0x93, 0x34, 0x6e, 0xda, 0x21, 0x71, 0xf3, 0xfb, 0xde, 0xf7, 0xf9, 0xf9, 0xbd, 0xf7,
	0x25, 0x70, 0x64, 0x30, 0x2f, 0x32, 0x66, 0x70, 0x54, 0x68, 0x65, 0x14, 0xd9, 0x37, 0xcb, 0x02,
	0xcb, 0x41, 0x9f, 0xab, 0x3c, 0x57, 0xb2, 0x02, 0xe9, 0x6b, 0x38, 0xbe, 0x92, 0x2c, 0x5b, 0x7e,
	0xc7, 0x69, 0xcd, 0x26, 0xcf, 0xa1, 0x37, 0x13, 0x98, 0xa5, 0x65, 0x14, 0x0c, 0x77, 0xcf, 0xc3,
	0xf1, 0xc9, 0xc8, 0x09, 0x47, 0x1f, 0x2c, 0x38, 0xb5, 0xc7, 0xb8, 0x26, 0xd0, 0x5f, 0x3b, 0x70,
	0x72, 0x25, 0x95, 0x5c, 0xe6, 0xc2, 0xbb, 0x80, 0xc0, 0x9e, 0x64, 0x39, 0x46, 0xc1, 0x30, 0x38,
	0x3f, 0x8c, 0xdd, 0x99, 0x0c, 0x21, 0x4c, 0x45, 0x59, 0x64, 0x6c, 0x79, 0x63, 0x53, 0x3b, 0x2e,
	0xe5, 0x43, 0x8e, 0x81, 0x25, 0xd7, 0xa2, 0x30, 0x42, 0xc9, 0x68, 0xb7, 0x66, 0xb4, 0x10, 0x39,
	0x03, 0xe0, 0x1a, 0x99, 0xc1, 0xa9, 0xc8, 0x31, 0xda, 0x73, 0x04, 0x0f, 0x21, 0x14, 0xfa, 0xb9,
	0x4a, 0xc5, 0x4c, 0x60, 0xea, 0x18, 0xfb, 0x8e, 0xb1, 0x86, 0x91, 0xaf, 0x10, 0xcd, 0x9a, 0x3e,
	0xa6, 0x9a, 0xc9, 0x72, 0xa6, 0x74, 0xce, 0xec, 0xf5, 0x65, 0xd4, 0x73, 0xed, 0x9e, 0x75, 0xdb,
	0x5d, 0xa7, 0xc5, 0x77, 0xea, 0xe9, 0xcf, 0x00, 0x1e, 0xdf, 0xa1, 0xfa, 0x8f, 0xa1, 0x92, 0x37,
	0x70, 0x64, 0xd6, 0xc4, 0x6e, 0x5a, 0xe1, 0xf8, 0x61, 0x2d, 0xe9, 0xbc, 0xa7, 0x43, 0xa6, 0xbf,
	0x03, 0x38, 0xea, 0x14, 0x1f, 0xc0, 0x81, 0xc4, 0x6f, 0x5f, 0x58, 0xb6, 0x68, 0x96, 0xb2, 0x8a,
	0xc9, 0x2b, 0xe8, 0x6b, 0x2c, 0x32, 0xc6, 0xb1, 0xca, 0x57, 0xb5, 0x1e, 0xd4, 0xb5, 0x62, 0x2f,
	0x15, 0xaf, 0x11, 0xc9, 0x4b, 0x08, 0x35, 0xa6, 0x8c, 0x9b, 0x4a, 0xb7, 0xeb, 0x74, 0x64, 0xa5,
	0x5b, 0x65, 0x62, 0x9f, 0x46, 0x2f, 0xa0, 0xef, 0xdf, 0xf9, 0xaf, 0xa7, 0xd1, 0x7b, 0x10, 0x7a,
	0xf7, 0x50, 0x0d, 0xf0, 0x9e, 0x19, 0x96, 0x08, 0x99, 0xa2, 0xb6, 0x42, 0x7b, 0xb2, 0xa3, 0x6b,
	0x84, 0x4d, 0x4c, 0x2e, 0xe0, 0x3e, 0x57, 0x52, 0x22, 0xb7, 0xdd, 0x4f, 0x8c, 0x16, 0x72, 0x5e,
	0x3b, 0x6e, 0x03, 0x27, 0xcf, 0xe0, 0xd0, 0xb0, 0x24, 0x43, 0x67, 0xcb, 0xca, 0x74, 0x2d, 0x40,
	0x3f, 0x02, 0x69, 0x6b, 0xae, 0x0c, 0xfe, 0x02, 0x20, 0x5d, 0xa1, 0x9d, 0x85, 0xb6, 0xf4, 0xd8,
	0x23, 0xd1, 0x1f, 0x70, 0xfa, 0x36, 0x53, 0xc9, 0xc4, 0x28, 0xcd, 0xe6, 0xf8, 0xae, 0x7a, 0x85,
	0xd2, 0xd6, 0xf5, 0x8c, 0x73, 0xb5, 0x90, 0xe6, 0xa6, 0xfd, 0x64, 0x7c, 0xc8, 0xba, 0xbe, 0x0e,
	0x3f, 0xe1, 0xb2, 0x6e, 0xc3, 0x43, 0xac, 0xeb, 0xb9, 0x92, 0x86, 0x09, 0xa9, 0xbd, 0x1e, 0xd6,
	0x30, 0xca, 0x20, 0x9c, 0x5c, 0xb6, 0x45, 0x07, 0x70, 0xc0, 0x38, 0xc7, 0xb2, 0xbc, 0x4e, 0x9b,
	0xd9, 0x35, 0x31, 0x79, 0x04, 0x3d, 0x8d, 0xf3, 0xc6, 0x75, 0x87, 0x71, 0x1d, 0xd9, 0x67, 0x24,
	0x0b, 0x7e, 0x8b, 0xc6, 0x2b, 0xe2, 0x21, 0xf4, 0x4f, 0x00, 0xc7, 0x13, 0xce, 0xa4, 0xf4, 0xe6,
	0x44, 0x60, 0xef, 0x56, 0xc8, 0xa6, 0x86, 0x3b, 0x93, 0xcf, 0x70, 0x9a, 0x6c, 0x19, 0x44, 0xed,
	0xbb, 0xa7, 0xf5, 0x14, 0xb7, 0xcd, 0x2a, 0xde, 0x2a, 0xb4, 0x3e, 0x2c, 0xdb, 0xde, 0x3a, 0x3e,
	0xf4, 0xba, 0x8e, 0x7d, 0x1a, 0xb9, 0x06, 0x92, 0x6e, 0x2c, 0xd6, 0xfd, 0x53, 0xc2, 0xf1, 0x93,
	0x8d, 0x55, 0x36, 0x84, 0x78, 0x8b, 0x28, 0xe9, 0xb9, 0x3f, 0xe9, 0xe5, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x39, 0xc9, 0xb0, 0x72, 0x70, 0x05, 0x00, 0x00,
}
