// Code generated by protoc-gen-go. DO NOT EDIT.
// source: template.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AnalyzeTemplate represents the analyze service template definition
type AnalyzeTemplate struct {
	Fields               []*FieldTypes `protobuf:"bytes,1,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AnalyzeTemplate) Reset()         { *m = AnalyzeTemplate{} }
func (m *AnalyzeTemplate) String() string { return proto.CompactTextString(m) }
func (*AnalyzeTemplate) ProtoMessage()    {}
func (*AnalyzeTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_2664e91c086be7f2, []int{0}
}
func (m *AnalyzeTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeTemplate.Unmarshal(m, b)
}
func (m *AnalyzeTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeTemplate.Marshal(b, m, deterministic)
}
func (dst *AnalyzeTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeTemplate.Merge(dst, src)
}
func (m *AnalyzeTemplate) XXX_Size() int {
	return xxx_messageInfo_AnalyzeTemplate.Size(m)
}
func (m *AnalyzeTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeTemplate proto.InternalMessageInfo

func (m *AnalyzeTemplate) GetFields() []*FieldTypes {
	if m != nil {
		return m.Fields
	}
	return nil
}

// AnonymizeTemplate represents the anonymize service template definition
type AnonymizeTemplate struct {
	Name                     string                     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DisplayName              string                     `protobuf:"bytes,2,opt,name=displayName" json:"displayName,omitempty"`
	Description              string                     `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	CreateTime               string                     `protobuf:"bytes,4,opt,name=createTime" json:"createTime,omitempty"`
	ModifiedTime             string                     `protobuf:"bytes,5,opt,name=modifiedTime" json:"modifiedTime,omitempty"`
	FieldTypeTransformations []*FieldTypeTransformation `protobuf:"bytes,6,rep,name=fieldTypeTransformations" json:"fieldTypeTransformations,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                   `json:"-"`
	XXX_unrecognized         []byte                     `json:"-"`
	XXX_sizecache            int32                      `json:"-"`
}

func (m *AnonymizeTemplate) Reset()         { *m = AnonymizeTemplate{} }
func (m *AnonymizeTemplate) String() string { return proto.CompactTextString(m) }
func (*AnonymizeTemplate) ProtoMessage()    {}
func (*AnonymizeTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_2664e91c086be7f2, []int{1}
}
func (m *AnonymizeTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnonymizeTemplate.Unmarshal(m, b)
}
func (m *AnonymizeTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnonymizeTemplate.Marshal(b, m, deterministic)
}
func (dst *AnonymizeTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnonymizeTemplate.Merge(dst, src)
}
func (m *AnonymizeTemplate) XXX_Size() int {
	return xxx_messageInfo_AnonymizeTemplate.Size(m)
}
func (m *AnonymizeTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_AnonymizeTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_AnonymizeTemplate proto.InternalMessageInfo

func (m *AnonymizeTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnonymizeTemplate) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *AnonymizeTemplate) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AnonymizeTemplate) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *AnonymizeTemplate) GetModifiedTime() string {
	if m != nil {
		return m.ModifiedTime
	}
	return ""
}

func (m *AnonymizeTemplate) GetFieldTypeTransformations() []*FieldTypeTransformation {
	if m != nil {
		return m.FieldTypeTransformations
	}
	return nil
}

// FieldTypeTransformation represents the transformation for array of fields types
type FieldTypeTransformation struct {
	Fields               []*FieldTypes   `protobuf:"bytes,1,rep,name=fields" json:"fields,omitempty"`
	Transformation       *Transformation `protobuf:"bytes,2,opt,name=transformation" json:"transformation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FieldTypeTransformation) Reset()         { *m = FieldTypeTransformation{} }
func (m *FieldTypeTransformation) String() string { return proto.CompactTextString(m) }
func (*FieldTypeTransformation) ProtoMessage()    {}
func (*FieldTypeTransformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_2664e91c086be7f2, []int{2}
}
func (m *FieldTypeTransformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldTypeTransformation.Unmarshal(m, b)
}
func (m *FieldTypeTransformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldTypeTransformation.Marshal(b, m, deterministic)
}
func (dst *FieldTypeTransformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldTypeTransformation.Merge(dst, src)
}
func (m *FieldTypeTransformation) XXX_Size() int {
	return xxx_messageInfo_FieldTypeTransformation.Size(m)
}
func (m *FieldTypeTransformation) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldTypeTransformation.DiscardUnknown(m)
}

var xxx_messageInfo_FieldTypeTransformation proto.InternalMessageInfo

func (m *FieldTypeTransformation) GetFields() []*FieldTypes {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *FieldTypeTransformation) GetTransformation() *Transformation {
	if m != nil {
		return m.Transformation
	}
	return nil
}

// Transformation represents the transformation type
type Transformation struct {
	NewValue             string        `protobuf:"bytes,1,opt,name=newValue" json:"newValue,omitempty"`
	ReplaceValue         *ReplaceValue `protobuf:"bytes,2,opt,name=replaceValue" json:"replaceValue,omitempty"`
	RedactValue          *RedactValue  `protobuf:"bytes,3,opt,name=redactValue" json:"redactValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Transformation) Reset()         { *m = Transformation{} }
func (m *Transformation) String() string { return proto.CompactTextString(m) }
func (*Transformation) ProtoMessage()    {}
func (*Transformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_2664e91c086be7f2, []int{3}
}
func (m *Transformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transformation.Unmarshal(m, b)
}
func (m *Transformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transformation.Marshal(b, m, deterministic)
}
func (dst *Transformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transformation.Merge(dst, src)
}
func (m *Transformation) XXX_Size() int {
	return xxx_messageInfo_Transformation.Size(m)
}
func (m *Transformation) XXX_DiscardUnknown() {
	xxx_messageInfo_Transformation.DiscardUnknown(m)
}

var xxx_messageInfo_Transformation proto.InternalMessageInfo

func (m *Transformation) GetNewValue() string {
	if m != nil {
		return m.NewValue
	}
	return ""
}

func (m *Transformation) GetReplaceValue() *ReplaceValue {
	if m != nil {
		return m.ReplaceValue
	}
	return nil
}

func (m *Transformation) GetRedactValue() *RedactValue {
	if m != nil {
		return m.RedactValue
	}
	return nil
}

type ReplaceValue struct {
	NewValue             string   `protobuf:"bytes,1,opt,name=newValue" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplaceValue) Reset()         { *m = ReplaceValue{} }
func (m *ReplaceValue) String() string { return proto.CompactTextString(m) }
func (*ReplaceValue) ProtoMessage()    {}
func (*ReplaceValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_2664e91c086be7f2, []int{4}
}
func (m *ReplaceValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceValue.Unmarshal(m, b)
}
func (m *ReplaceValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceValue.Marshal(b, m, deterministic)
}
func (dst *ReplaceValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceValue.Merge(dst, src)
}
func (m *ReplaceValue) XXX_Size() int {
	return xxx_messageInfo_ReplaceValue.Size(m)
}
func (m *ReplaceValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceValue.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceValue proto.InternalMessageInfo

func (m *ReplaceValue) GetNewValue() string {
	if m != nil {
		return m.NewValue
	}
	return ""
}

type RedactValue struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedactValue) Reset()         { *m = RedactValue{} }
func (m *RedactValue) String() string { return proto.CompactTextString(m) }
func (*RedactValue) ProtoMessage()    {}
func (*RedactValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_2664e91c086be7f2, []int{5}
}
func (m *RedactValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedactValue.Unmarshal(m, b)
}
func (m *RedactValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedactValue.Marshal(b, m, deterministic)
}
func (dst *RedactValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedactValue.Merge(dst, src)
}
func (m *RedactValue) XXX_Size() int {
	return xxx_messageInfo_RedactValue.Size(m)
}
func (m *RedactValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RedactValue.DiscardUnknown(m)
}

var xxx_messageInfo_RedactValue proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AnalyzeTemplate)(nil), "types.AnalyzeTemplate")
	proto.RegisterType((*AnonymizeTemplate)(nil), "types.AnonymizeTemplate")
	proto.RegisterType((*FieldTypeTransformation)(nil), "types.FieldTypeTransformation")
	proto.RegisterType((*Transformation)(nil), "types.Transformation")
	proto.RegisterType((*ReplaceValue)(nil), "types.ReplaceValue")
	proto.RegisterType((*RedactValue)(nil), "types.RedactValue")
}

func init() { proto.RegisterFile("template.proto", fileDescriptor_template_2664e91c086be7f2) }

var fileDescriptor_template_2664e91c086be7f2 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0xc6, 0x95, 0xfe, 0xd3, 0xfb, 0x5e, 0x42, 0x51, 0x8d, 0x10, 0x51, 0x87, 0xaa, 0xf2, 0x54,
	0x18, 0x3a, 0x14, 0x24, 0x16, 0x18, 0xba, 0x30, 0x32, 0x44, 0x11, 0x03, 0x9b, 0x49, 0x2e, 0x92,
	0xa5, 0xd8, 0x8e, 0x1c, 0x23, 0x14, 0x56, 0x46, 0x3e, 0x02, 0x5f, 0x16, 0xc5, 0x49, 0x83, 0x13,
	0xa9, 0x48, 0x6c, 0xce, 0xf3, 0xfc, 0x9e, 0x3b, 0xdf, 0xc5, 0x30, 0x37, 0x28, 0x8a, 0x9c, 0x19,
	0xdc, 0x16, 0x5a, 0x19, 0x45, 0xa6, 0xa6, 0x2a, 0xb0, 0x5c, 0x06, 0x89, 0x12, 0x42, 0xc9, 0x46,
	0xa4, 0x77, 0x70, 0xba, 0x97, 0x2c, 0xaf, 0xde, 0x31, 0x6e, 0x69, 0x72, 0x09, 0xb3, 0x8c, 0x63,
	0x9e, 0x96, 0xa1, 0xb7, 0x1e, 0x6f, 0xfc, 0xdd, 0x62, 0x6b, 0x83, 0xdb, 0x87, 0x5a, 0x8c, 0xeb,
	0x63, 0xd4, 0x02, 0xf4, 0x73, 0x04, 0x8b, 0xbd, 0x54, 0xb2, 0x12, 0xdc, 0x29, 0x40, 0x60, 0x22,
	0x99, 0xc0, 0xd0, 0x5b, 0x7b, 0x9b, 0xff, 0x91, 0x3d, 0x93, 0x35, 0xf8, 0x29, 0x2f, 0x8b, 0x9c,
	0x55, 0x8f, 0xb5, 0x35, 0xb2, 0x96, 0x2b, 0x59, 0x02, 0xcb, 0x44, 0xf3, 0xc2, 0x70, 0x25, 0xc3,
	0x71, 0x4b, 0xfc, 0x48, 0x64, 0x05, 0x90, 0x68, 0x64, 0x06, 0x63, 0x2e, 0x30, 0x9c, 0x58, 0xc0,
	0x51, 0x08, 0x85, 0x40, 0xa8, 0x94, 0x67, 0x1c, 0x53, 0x4b, 0x4c, 0x2d, 0xd1, 0xd3, 0xc8, 0x33,
	0x84, 0xd9, 0x61, 0x8e, 0x58, 0x33, 0x59, 0x66, 0x4a, 0x0b, 0x56, 0x97, 0x2f, 0xc3, 0x99, 0x1d,
	0x77, 0x35, 0x1c, 0xb7, 0x8f, 0x45, 0x47, 0xf3, 0xf4, 0xc3, 0x83, 0x8b, 0x23, 0xa9, 0x3f, 0x2c,
	0x95, 0xdc, 0xc3, 0xdc, 0xf4, 0xc2, 0x76, 0x5b, 0xfe, 0xee, 0xbc, 0x8d, 0x0c, 0xee, 0x33, 0x80,
	0xe9, 0x97, 0x07, 0xf3, 0x41, 0xf3, 0x25, 0xfc, 0x93, 0xf8, 0xf6, 0xc4, 0xf2, 0xd7, 0xc3, 0x4f,
	0xe9, 0xbe, 0xc9, 0x2d, 0x04, 0x1a, 0x8b, 0x9c, 0x25, 0xd8, 0xf8, 0x4d, 0xaf, 0xb3, 0xb6, 0x57,
	0xe4, 0x58, 0x51, 0x0f, 0x24, 0x37, 0xe0, 0x6b, 0x4c, 0x59, 0x62, 0x9a, 0xdc, 0xd8, 0xe6, 0x48,
	0x97, 0xeb, 0x9c, 0xc8, 0xc5, 0xe8, 0x15, 0x04, 0x6e, 0xcd, 0xdf, 0xae, 0x46, 0x4f, 0xc0, 0x77,
	0xea, 0xbc, 0xcc, 0xec, 0x8b, 0xbd, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x77, 0x7a, 0x80, 0xaf,
	0xd8, 0x02, 0x00, 0x00,
}
