compiler:
  - gcc
matrix:
  include:
    - language: python
      cache: pip
      python:
        - "3.6"
      install:
      - pip install grpcio-tools
      - pip install googleapis-common-protos
      script:
      - cd src
      - python -m grpc_tools.protoc -I . --python_out=../python --grpc_python_out=../python ./*.proto
    - language: go
      go:
      - "1.10"
      install:
      - go get -v google.golang.org/grpc
      - go get -v github.com/golang/protobuf/...
      - mkdir ../protoc
      - |
        (
        cd ../protoc
        wget "https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-${TRAVIS_OS_NAME}-x86_64.zip"
        unzip "protoc-3.5.1-${TRAVIS_OS_NAME}-x86_64.zip"
        )
      - export PATH="$(pwd)/../protoc/bin:$PATH"
      script:
      - cd src
      - protoc -I . --go_out=plugins=grpc:../golang ./*.proto

