# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import databinder_pb2 as databinder__pb2


class DatabinderServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Apply = channel.unary_unary(
        '/types.DatabinderService/Apply',
        request_serializer=databinder__pb2.DatabinderRequest.SerializeToString,
        response_deserializer=databinder__pb2.DatabinderResponse.FromString,
        )


class DatabinderServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Apply(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DatabinderServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Apply': grpc.unary_unary_rpc_method_handler(
          servicer.Apply,
          request_deserializer=databinder__pb2.DatabinderRequest.FromString,
          response_serializer=databinder__pb2.DatabinderResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'types.DatabinderService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
