# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import template_pb2 as template__pb2
import scan_pb2 as scan__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='job.proto',
  package='types',
  syntax='proto3',
  serialized_pb=_b('\n\tjob.proto\x12\x05types\x1a\x0etemplate.proto\x1a\nscan.proto\"y\n\nJobRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1f\n\x07trigger\x18\x03 \x01(\x0b\x32\x0e.types.Trigger\x12\'\n\x0bscanRequest\x18\x04 \x01(\x0b\x32\x12.types.ScanRequest\"\r\n\x0bJobResponse2>\n\nJobService\x12\x30\n\x05\x41pply\x12\x11.types.JobRequest\x1a\x12.types.JobResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[template__pb2.DESCRIPTOR,scan__pb2.DESCRIPTOR,])




_JOBREQUEST = _descriptor.Descriptor(
  name='JobRequest',
  full_name='types.JobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='types.JobRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='types.JobRequest.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trigger', full_name='types.JobRequest.trigger', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scanRequest', full_name='types.JobRequest.scanRequest', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=169,
)


_JOBRESPONSE = _descriptor.Descriptor(
  name='JobResponse',
  full_name='types.JobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=184,
)

_JOBREQUEST.fields_by_name['trigger'].message_type = template__pb2._TRIGGER
_JOBREQUEST.fields_by_name['scanRequest'].message_type = scan__pb2._SCANREQUEST
DESCRIPTOR.message_types_by_name['JobRequest'] = _JOBREQUEST
DESCRIPTOR.message_types_by_name['JobResponse'] = _JOBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobRequest = _reflection.GeneratedProtocolMessageType('JobRequest', (_message.Message,), dict(
  DESCRIPTOR = _JOBREQUEST,
  __module__ = 'job_pb2'
  # @@protoc_insertion_point(class_scope:types.JobRequest)
  ))
_sym_db.RegisterMessage(JobRequest)

JobResponse = _reflection.GeneratedProtocolMessageType('JobResponse', (_message.Message,), dict(
  DESCRIPTOR = _JOBRESPONSE,
  __module__ = 'job_pb2'
  # @@protoc_insertion_point(class_scope:types.JobResponse)
  ))
_sym_db.RegisterMessage(JobResponse)



_JOBSERVICE = _descriptor.ServiceDescriptor(
  name='JobService',
  full_name='types.JobService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=186,
  serialized_end=248,
  methods=[
  _descriptor.MethodDescriptor(
    name='Apply',
    full_name='types.JobService.Apply',
    index=0,
    containing_service=None,
    input_type=_JOBREQUEST,
    output_type=_JOBRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_JOBSERVICE)

DESCRIPTOR.services_by_name['JobService'] = _JOBSERVICE

# @@protoc_insertion_point(module_scope)
