# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import job_pb2 as job__pb2


class JobServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Apply = channel.unary_unary(
        '/types.JobService/Apply',
        request_serializer=job__pb2.JobRequest.SerializeToString,
        response_deserializer=job__pb2.JobResponse.FromString,
        )


class JobServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Apply(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Apply': grpc.unary_unary_rpc_method_handler(
          servicer.Apply,
          request_deserializer=job__pb2.JobRequest.FromString,
          response_serializer=job__pb2.JobResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'types.JobService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
